# season id 748 is the first one where the arenas are all correct

In [2]:
import pandas as pd
import numpy as np
import plotly.plotly as py
import plotly.graph_objs as go

In [3]:
series_id = '748'

In [4]:
df = pd.read_csv('mfp_all_seasons_full.csv')

In [30]:
df.Arena = df.Arena.str.strip()

In [31]:
will = df[df['players'] == 'Will Chernetsky']
lucy = df[df['players'] == 'Lucy Cachux']

In [32]:
set(df.Arena.unique())-set(will.Arena.unique())

{'Bram Stokers Dracula',
 'Bride of Pinbot 2.0',
 'Evel Knievel',
 'FLASH',
 'Iron Maiden',
 'Johnny Mnemonic',
 'Lost In Space',
 'Popeye',
 'The Addams Family',
 'The Shadow',
 'The Wizard of Oz Emerald City LE'}

In [35]:
lucy[lucy.round_number == 5]

,Arena,Time,Unnamed: 0,adj_time,group_number,num_players,places,players,points,positions,round_number,season_id
131,Congo,1773,131,1773.000000,1,4,4th,Lucy Cachux,1,4,5,748
284,Baywatch,1247,284,1247.000000,3,4,3rd,Lucy Cachux,3,1,5,748
408,Tron,635,408,846.666667,6,3,1st,Lucy Cachux,7,2,5,748
496,WWF Royal Rumble,776,496,776.000000,3,4,4th,Lucy Cachux,1,3,5,748
648,Flash Gordon,521,648,521.000000,6,4,2nd,Lucy Cachux,5,1,5,748
750,Old Chicago,1104,750,1104.000000,2,4,1st,Lucy Cachux,7,4,5,748
880,X-Men,1720,880,1720.000000,2,4,3rd,Lucy Cachux,3,1,5,748
1032,Batman Dark Knight,1432,1032,1432.000000,2,4,4th,Lucy Cachux,1,1,5,748
1152,Doctor Who,1191,1152,1191.000000,3,4,2nd,Lucy Cachux,5,2,5,748
1272,X-Men,1602,1272,1602.000000,2,4,1st,Lucy Cachux,7,3,5,748
1384,Doctor Who,1106,93,1106.000000,2,4,2nd,Lucy Cachux,5,2,5,861
1486,Doctor Who,808,195,808.000000,1,4,1st,Lucy Cachux,7,2,5,861
1607,Spider-Man,1248,316,1248.000000,1,4,4th,Lucy Cachux,1,2,5,861
1711,Spider-Man,892,420,892.000000,1,4,2nd,Lucy Cachux,5,1,5,861
1828,Tron,1205,537,1205.000000,1,4,2nd,Lucy Cachux,5,4,5,861
1989,Pirates of the Caribbean,839,698,839.000000,2,4,1st,Lucy Cachux,7,4,5,861
2114,Funhouse,698,823,698.000000,1,4,1st,Lucy Cachux,7,3,5,861
2259,The Big Lebowksi,931,968,931.000000,1,4,1st,Lucy Cachux,7,1,5,861
2415,Funhouse,780,1124,780.000000,4,4,1st,Lucy Cachux,7,2,5,861
2562,Paragon,639,1271,639.000000,5,4,1st,Lucy Cachux,7,2,5,861
2666,Total Nuclear Annihilation,1286,92,1286.000000,2,4,2nd,Lucy Cachux,5,2,5,987
2815,Pirates of the Caribbean,1431,241,1431.000000,1,4,2nd,Lucy Cachux,5,1,5,987
2980,Pirates of the Caribbean,898,406,898.000000,4,4,2nd,Lucy Cachux,5,1,5,987
3127,Paragon,562,553,562.000000,2,4,1st,Lucy Cachux,7,3,5,987
3291,Metallica,844,717,844.000000,2,4,1st,Lucy Cachux,7,4,5,987
3447,White Water,837,873,837.000000,5,4,1st,Lucy Cachux,7,1,5,987
3635,The Walking Cora,747,1061,747.000000,5,4,3rd,Lucy Cachux,3,2,5,987
3770,Attack From Mars,546,1196,546.000000,4,4,1st,Lucy Cachux,7,1,5,987
3882,White Water,1056,1308,1056.000000,2,4,1st,Lucy Cachux,7,3,5,987
4000,2001,752,1426,752.000000,1,4,1st,Lucy Cachux,7,2,5,987
4158,Eight Ball Deluxe,843,134,843.000000,1,4,2nd,Lucy Cachux,5,4,5,1080
4311,Playboy '02,856,287,856.000000,1,4,1st,Lucy Cachux,7,1,5,1080
4498,Eight Ball Deluxe,610,474,610.000000,2,4,1st,Lucy Cachux,7,2,5,1080
4683,Buccaneer,991,659,991.000000,3,4,1st,Lucy Cachux,7,1,5,1080
4845,Hokus Pokus,886,821,886.000000,2,4,3rd,Lucy Cachux,3,3,5,1080
5031,The Walking Dead,1085,1007,1085.000000,4,4,3rd,Lucy Cachux,3,2,5,1080
5223,Terminator 2,1501,1199,1501.000000,3,4,4th,Lucy Cachux,1,3,5,1080
5437,Attack From Mars,538,1413,538.000000,6,4,2nd,Lucy Cachux,5,1,5,1080
5618,The Getaway: High Speed II,880,1594,880.000000,6,4,2nd,Lucy Cachux,5,4,5,1080
5767,2001,562,1743,562.000000,5,4,2nd,Lucy Cachux,5,3,5,1080
5931,Doctor Who,528,152,528.000000,1,4,4th,Lucy Cachux,1,1,5,1194
6106,The Big Lebowski,1252,327,1252.000000,4,4,3rd,Lucy Cachux,3,2,5,1194
6252,Jacks Open,630,473,630.000000,6,4,1st,Lucy Cachux,7,1,5,1194
6377,Jacks Open,731,598,731.000000,1,4,3rd,Lucy Cachux,3,4,5,1194
6535,Paragon,740,756,740.000000,2,4,2nd,Lucy Cachux,5,2,5,1194
6705,Disney TRON: Legacy (LE),1181,926,1181.000000,1,4,2nd,Lucy Cachux,5,4,5,1194
6873,The Hobbit (LE),924,1094,924.000000,1,4,4th,Lucy Cachux,1,1,5,1194
7067,Congo,840,1288,840.000000,7,4,1st,Lucy Cachux,7,2,5,1194
7225,Dirty Harry,594,1446,594.000000,3,4,4th,Lucy Cachux,1,2,5,1194
7398,No Fear: Dangerous Sports,1074,1619,1074.000000,3,4,3rd,Lucy Cachux,3,4,5,1194

In [13]:
lucy.groupby('Arena').mean().sort_values('points',ascending=False)

,Time,Unnamed: 0,adj_time,group_number,num_players,points,positions,round_number,season_id
Arena,,,,,,,,,
Elvis Gold,818.000000,747.000000,818.000000,6.000000,4.000000,7.000000,3.000000,1.000000,861.000000
The Hobbit,945.500000,534.250000,1002.250000,3.250000,3.750000,7.000000,2.250000,2.750000,864.250000
Funhouse,739.000000,973.500000,739.000000,2.500000,4.000000,7.000000,2.500000,5.000000,861.000000
The Shadow,963.000000,796.000000,963.000000,4.000000,4.000000,7.000000,2.000000,4.000000,1080.000000
The Big Lebowksi,931.000000,968.000000,931.000000,1.000000,4.000000,7.000000,1.000000,5.000000,861.000000
Attack From Mars,728.428571,677.428571,757.142857,3.714286,3.857143,6.714286,2.285714,3.000000,879.857143
Godzilla,1006.333333,524.000000,1006.333333,2.333333,4.000000,6.333333,2.333333,2.666667,1125.000000
Paragon,599.714286,814.142857,610.761905,4.428571,3.928571,6.142857,2.571429,3.142857,1021.142857
Dealer's Choice,802.500000,552.000000,802.500000,2.250000,4.000000,6.000000,2.250000,1.250000,864.250000
The Walking Cora,1057.000000,741.500000,1057.000000,2.000000,4.000000,6.000000,2.750000,3.250000,1059.000000
Sorcerer,813.000000,603.750000,856.250000,3.750000,3.750000,5.750000,3.000000,1.750000,975.750000
Buccaneer,836.428571,746.000000,866.380952,3.714286,3.857143,5.714286,2.000000,2.571429,843.857143
Family Guy,769.333333,819.333333,769.333333,3.000000,4.000000,5.666667,3.333333,3.666667,1045.333333
Disney TRON: Legacy (LE),1109.333333,913.833333,1147.222222,4.000000,3.833333,5.666667,2.166667,2.833333,1047.000000
Total Nuclear Annihilation,949.833333,675.833333,975.500000,3.666667,3.833333,5.333333,2.666667,3.000000,960.666667
Star Trek: The Next Generation,793.000000,814.833333,827.722222,4.166667,3.833333,5.166667,2.833333,2.166667,1007.166667
The Addams Family,972.500000,830.000000,972.500000,1.500000,4.000000,5.000000,2.500000,1.500000,804.500000
Flash Gordon,521.000000,648.000000,521.000000,6.000000,4.000000,5.000000,1.000000,5.000000,748.000000
The Hobbit (LE),863.400000,1022.400000,863.400000,2.400000,4.000000,5.000000,2.000000,3.000000,1171.200000
White Water,1114.333333,1186.333333,1114.333333,2.666667,4.000000,5.000000,2.666667,4.333333,987.000000
Hokus Pokus,908.800000,564.100000,926.933333,3.800000,3.900000,5.000000,2.300000,2.500000,983.300000
Space Shuttle,763.000000,921.000000,763.000000,2.333333,4.000000,5.000000,2.666667,3.333333,987.000000
The Hobbit (Smaug Edition),784.333333,597.666667,784.333333,2.666667,4.000000,5.000000,2.666667,2.000000,1049.000000
Road Kings,645.000000,742.333333,645.000000,2.666667,4.000000,5.000000,2.333333,3.333333,785.666667
Playboy '02,838.000000,583.714286,838.000000,3.142857,4.000000,5.000000,2.285714,2.571429,995.571429
Old Chicago,720.666667,504.000000,763.592593,3.333333,3.777778,5.000000,2.333333,3.111111,826.222222
2001,746.909091,691.636364,766.939394,3.454545,3.909091,4.818182,2.272727,3.090909,993.181818
World Cup Soccer,839.285714,546.857143,839.285714,2.857143,4.000000,4.714286,2.857143,2.428571,989.142857
No Fear: Dangerous Sports,823.666667,633.000000,823.666667,4.000000,4.000000,4.666667,2.666667,2.666667,1056.000000
The Big Lebowski,1040.500000,666.666667,1040.500000,4.500000,4.000000,4.666667,2.166667,2.666667,1137.000000
Congo,995.833333,821.833333,995.833333,4.000000,4.000000,4.666667,3.500000,2.833333,1062.666667
Dirty Harry,795.166667,1108.666667,835.777778,3.333333,3.833333,4.666667,2.666667,3.000000,1031.666667
Eight Ball Deluxe,678.666667,719.000000,678.666667,2.333333,4.000000,4.333333,2.333333,4.666667,1080.000000
X-Men,1503.000000,912.333333,1503.000000,3.000000,4.000000,4.333333,2.666667,4.333333,748.000000
Jacks Open,686.000000,586.000000,686.000000,2.666667,4.000000,4.333333,2.000000,4.333333,1194.000000
The Getaway: High Speed II,979.800000,1004.400000,979.800000,2.800000,4.000000,4.200000,3.800000,2.600000,1107.000000
Pirates of the Caribbean,1286.000000,685.142857,1286.000000,2.714286,4.000000,4.142857,2.428571,3.142857,964.285714
WWF Royal Rumble,815.000000,588.000000,815.000000,2.000000,4.000000,4.000000,2.000000,3.500000,748.000000
Tron,999.833333,597.166667,1035.111111,3.166667,3.833333,4.000000,2.833333,3.500000,785.666667
Bram Stokers Dracula,419.000000,1258.000000,558.666667,8.000000,3.000000,4.000000,2.000000,4.000000,1194.000000
Doctor Who,818.300000,720.600000,852.200000,2.900000,3.900000,3.800000,2.000000,3.800000,1030.000000
Terminator 2,1177.800000,1208.600000,1177.800000,4.400000,4.000000,3.800000,2.000000,3.200000,1148.400000
Indianapolis 500,683.000000,846.833333,738.666667,3.833333,3.666667,3.666667,2.666667,2.333333,922.833333
F-14 Tomcat,652.500000,261.500000,652.500000,3.000000,4.000000,3.500000,2.500000,2.750000,832.750000
Star Trek (Pro),962.500000,558.000000,962.500000,2.500000,4.000000,3.500000,2.750000,3.750000,916.000000
Batman Dark Knight,1056.200000,725.800000,1056.200000,2.200000,4.000000,3.400000,1.800000,3.800000,888.800000
Metallica,888.666667,650.166667,888.666667,2.333333,4.000000,3.333333,2.833333,2.666667,806.666667
Houdini: Master of Mystery,898.000000,831.833333,924.000000,3.000000,3.833333,3.166667,2.333333,2.333333,1137.000000
Sky Kings,798.000000,1647.000000,798.000000,4.000000,4.000000,3.000000,1.000000,2.000000,1080.000000
Jurassic Park (Pro),934.000000,1406.000000,934.000000,2.000000,4.000000,3.000000,1.000000,4.000000,1194.000000
Spider-Man,1070.000000,368.000000,1070.000000,1.000000,4.000000,3.000000,1.500000,5.000000,861.000000
Beatles,903.000000,175.000000,903.000000,1.000000,4.000000,3.000000,3.000000,4.000000,861.000000
The Walking Dead,1102.500000,1238.000000,1102.500000,2.500000,4.000000,3.000000,1.500000,3.500000,1080.000000
Iron Man,1389.000000,877.000000,1389.000000,8.000000,4.000000,3.000000,3.000000,1.000000,1080.000000
Lost In Space,959.000000,252.000000,959.000000,2.000000,4.000000,3.000000,2.000000,4.000000,748.000000
Baywatch,1077.000000,422.666667,1153.000000,3.666667,3.666667,2.333333,2.333333,3.333333,827.666667
Sky Jump,807.000000,309.000000,807.000000,2.000000,4.000000,1.000000,1.000000,1.000000,748.000000

In [9]:
df.groupby(['players','round_number']).mean()

                                      Time   Unnamed: 0     adj_time  \
players          round_number
"Andrea"         1             1412.000000   522.000000  1412.000000
                 2              956.000000   571.000000   956.000000
                 3              739.000000   611.000000   739.000000
                 4             1372.000000   650.000000  1372.000000
                 5              912.000000   683.000000   912.000000
"Blaise"         1              760.000000   910.000000   760.000000
                 2              812.000000   938.000000   812.000000
                 3              624.000000   982.000000   624.000000
                 4             1260.000000  1016.000000  1260.000000
                 5              717.000000  1040.000000   717.000000
"Cody"           1              792.000000  1074.000000  1056.000000
                 2              679.000000  1097.000000   905.333333
                 3             1176.000000  1109.000000  1176.000000
                 4              743.000000  1138.000000   990.666667
                 5              466.000000  1163.000000   621.333333
"Penelope"       1              597.000000  1071.000000   796.000000
                 2             1030.000000  1099.000000  1373.333333
                 3              377.000000  1121.000000   502.666667
                 4              621.000000  1140.000000   828.000000
                 5              466.000000  1161.000000   621.333333
Aalono Steck     1              983.000000   759.000000   983.000000
                 2              903.000000   793.000000  1204.000000
                 3              629.000000   828.000000   838.666667
Aaron Rossi      1              836.000000   489.000000   836.000000
                 2              919.000000   527.000000   919.000000
                 3              808.000000   554.000000   808.000000
                 4              903.000000   579.000000   903.000000
                 5              663.000000   615.000000   663.000000
Adam Venuti      1              882.000000   567.000000   882.000000
                 2              876.000000   601.000000   876.000000
...                                    ...          ...          ...
Will Chernetsky  1              790.380000   675.660000   838.386667
                 2              847.240000   702.320000   885.100000
                 3              836.340000   730.840000   857.653333
                 4              822.420000   760.060000   833.980000
                 5              883.100000   788.640000   908.200000
William E Rubley 1              928.000000   427.000000   928.000000
                 2              855.000000   460.000000   855.000000
                 3              893.000000   499.000000   893.000000
                 4              841.000000   527.000000   841.000000
                 5              562.000000   554.000000   562.000000
Xavier Marin     1              938.000000   618.500000   938.000000
                 2              901.000000   651.000000   901.000000
                 3              912.500000   677.500000   912.500000
                 4              939.000000   708.000000   939.000000
                 5              679.500000   735.000000   679.500000
Zack Stephens    1             1149.000000   589.000000  1149.000000
                 2             1092.500000   343.500000  1323.833333
                 3              832.000000   665.000000   832.000000
                 4              648.000000   705.000000   864.000000
                 5              551.000000   741.000000   734.666667
“Iris”           1              865.000000   665.448276   901.896552
                 2              810.172414   699.241379   870.942529
                 3              831.724138   728.034483   883.586207
                 4              858.000000   757.586207   892.666667
                 5              824.827586   789.275862   877.494253
“RC”             1              744.928571   649.678571   777.261905
                 2              895.607143   676.500000   923.023810
                 3              826.535714   708.750000   886.869048
                 4              814.428571   735.821429   856.380952
                 5              897.857143   764.964286   914.023810

                               group_number  num_players    points  positions  \
players          round_number
"Andrea"         1                 4.000000     4.000000  1.000000   4.000000
                 2                 8.000000     4.000000  3.000000   1.000000
                 3                 9.000000     4.000000  1.000000   1.000000
                 4                 9.000000     4.000000  1.000000   4.000000
                 5                 9.000000     4.000000  1.000000   1.000000
"Blaise"         1                 2.000000     4.000000  7.000000   3.000000
                 2                 1.000000     4.000000  1.000000   4.000000
                 3                 5.000000     4.000000  3.000000   1.000000
                 4                 5.000000     4.000000  5.000000   4.000000
                 5                 4.000000     4.000000  5.000000   1.000000
"Cody"           1                 5.000000     3.000000  1.000000   1.000000
                 2                 5.000000     3.000000  7.000000   3.000000
                 3                 3.000000     4.000000  1.000000   1.000000
                 4                 5.000000     3.000000  1.000000   2.000000
                 5                 6.000000     3.000000  4.000000   3.000000
"Penelope"       1                 4.000000     3.000000  1.000000   1.000000
                 2                 6.000000     3.000000  1.000000   2.000000
                 3                 6.000000     3.000000  1.000000   3.000000
                 4                 6.000000     3.000000  1.000000   1.000000
                 5                 6.000000     3.000000  1.000000   1.000000
Aalono Steck     1                 5.000000     4.000000  1.000000   1.000000
                 2                 6.000000     3.000000  1.000000   2.000000
                 3                 8.000000     3.000000  4.000000   2.000000
Aaron Rossi      1                 3.000000     4.000000  1.000000   2.000000
                 2                 6.000000     4.000000  5.000000   1.000000
                 3                 5.000000     4.000000  5.000000   4.000000
                 4                 4.000000     4.000000  1.000000   3.000000
                 5                 6.000000     4.000000  1.000000   1.000000
Adam Venuti      1                 3.000000     4.000000  5.000000   3.000000
                 2                 4.000000     4.000000  3.000000   1.000000
...                                     ...          ...       ...        ...
Will Chernetsky  1                 4.480000     3.780000  4.520000   2.300000
                 2                 3.780000     3.820000  4.740000   2.120000
                 3                 3.400000     3.880000  4.760000   2.440000
                 4                 3.180000     3.940000  4.500000   2.760000
                 5                 3.060000     3.900000  4.700000   2.160000
William E Rubley 1                 1.000000     4.000000  7.000000   4.000000
                 2                 2.000000     4.000000  1.000000   3.000000
                 3                 4.000000     4.000000  5.000000   3.000000
                 4                 3.000000     4.000000  7.000000   4.000000
                 5                 2.000000     4.000000  1.000000   4.000000
Xavier Marin     1                 6.000000     4.000000  2.000000   2.500000
                 2                 6.000000     4.000000  7.000000   1.000000
                 3                 4.000000     4.000000  6.000000   1.500000
                 4                 3.000000     4.000000  6.000000   2.000000
                 5                 1.500000     4.000000  3.000000   1.000000
Zack Stephens    1                 3.000000     4.000000  5.000000   4.000000
                 2                 6.000000     3.500000  4.000000   3.000000
                 3                 6.000000     4.000000  1.000000   2.000000
                 4                 8.000000     3.000000  1.000000   2.000000
                 5                 9.000000     3.000000  4.000000   2.000000
“Iris”           1                 3.931034     3.827586  3.206897   2.758621
                 2                 5.172414     3.724138  3.896552   2.206897
                 3                 4.965517     3.724138  3.862069   2.068966
                 4                 4.862069     3.793103  2.793103   2.172414
                 5                 5.310345     3.724138  3.586207   2.586207
“RC”             1                 4.607143     3.821429  4.464286   2.535714
                 2                 3.892857     3.892857  3.107143   2.535714
                 3                 4.535714     3.714286  4.964286   2.392857
                 4                 3.928571     3.821429  4.535714   2.035714
                 5                 3.607143     3.928571  4.250000   2.607143

                                 season_id
players          round_number
"Andrea"         1             1080.000000
                 2             1080.000000
                 3             1080.000000
                 4             1080.000000
                 5             1080.000000
"Blaise"         1              748.000000
                 2              748.000000
                 3              748.000000
                 4              748.000000
                 5              748.000000
"Cody"           1              748.000000
                 2              748.000000
                 3              748.000000
                 4              748.000000
                 5              748.000000
"Penelope"       1              748.000000
                 2              748.000000
                 3              748.000000
                 4              748.000000
                 5              748.000000
Aalono Steck     1              987.000000
                 2              987.000000
                 3              987.000000
Aaron Rossi      1             1194.000000
                 2             1194.000000
                 3             1194.000000
                 4             1194.000000
                 5             1194.000000
Adam Venuti      1              861.000000
                 2              861.000000
...                                    ...
Will Chernetsky  1              974.000000
                 2              974.000000
                 3              974.000000
                 4              974.000000
                 5              974.000000
William E Rubley 1              987.000000
                 2              987.000000
                 3              987.000000
                 4              987.000000
                 5              987.000000
Xavier Marin     1             1080.000000
                 2             1080.000000
                 3             1080.000000
                 4             1080.000000
                 5             1080.000000
Zack Stephens    1              987.000000
                 2             1033.500000
                 3              987.000000
                 4              987.000000
                 5              987.000000
“Iris”           1              910.344828
                 2              910.344828
                 3              910.344828
                 4              910.344828
                 5              910.344828
“RC”             1              916.142857
                 2              916.142857
                 3              916.142857
                 4              916.142857
                 5              916.142857

[741 rows x 8 columns]

In [10]:
df.groupby('players').mean().sort_values('adj_time',ascending=False)

,Time,Unnamed: 0,adj_time,group_number,num_players,points,positions,round_number,season_id
players,,,,,,,,,
Peter Plachta,1043.000000,881.000000,1390.666667,7.000000,3.000000,7.000000,1.000000,5.000000,987.000000
Diana Crespo,1034.000000,440.000000,1378.666667,6.000000,3.000000,7.000000,2.000000,5.000000,861.000000
R.J. Méndez,1034.000000,441.000000,1378.666667,6.000000,3.000000,1.000000,3.000000,5.000000,861.000000
John Steck,1070.250000,814.750000,1244.250000,6.000000,3.500000,1.500000,2.750000,2.750000,987.000000
Scott Brown,867.000000,1209.000000,1156.000000,7.000000,3.000000,1.000000,3.000000,5.000000,987.000000
"""Andrea""",1078.200000,607.400000,1078.200000,7.800000,4.000000,1.400000,2.200000,3.000000,1080.000000
Haakon Hestness,862.200000,591.800000,1074.200000,7.000000,3.400000,2.800000,2.600000,3.000000,748.000000
Selena DeLeon,831.200000,932.800000,1057.466667,7.400000,3.200000,1.000000,2.000000,3.000000,861.000000
Sam Paredes,951.400000,1144.800000,1057.200000,9.600000,3.600000,2.000000,1.800000,3.000000,1080.000000
Zack Stephens,894.166667,564.500000,1037.888889,6.333333,3.500000,3.166667,2.666667,2.833333,1002.500000
Aalono Steck,838.333333,793.333333,1008.555556,6.333333,3.333333,2.000000,1.666667,2.000000,987.000000
Breanna Lane,791.000000,952.200000,1007.066667,9.000000,3.200000,3.400000,2.200000,3.000000,1080.000000
Nate Nielsen,964.645161,602.419355,996.774194,5.000000,3.903226,4.193548,2.354839,3.096774,1094.709677
Michael Delgrosso,995.600000,406.000000,995.600000,3.800000,4.000000,4.600000,2.800000,3.000000,1080.000000
Todd Brammer,948.930000,837.120000,993.526667,4.890000,3.830000,3.740000,2.430000,3.000000,1033.750000
Greg Dunlap,992.200000,1291.500000,992.200000,3.200000,4.000000,5.400000,2.600000,3.000000,1194.000000
Dan Phillips,776.600000,1218.600000,991.733333,6.600000,3.200000,2.800000,2.000000,3.000000,861.000000
Matthew Talley,971.551020,718.677551,982.527891,3.048980,3.951020,4.804082,2.526531,3.000000,973.734694
Leonard Lazarus,916.800000,1046.800000,973.066667,5.800000,3.800000,3.400000,2.600000,3.000000,1194.000000
Nick Fitzpatrick,937.136000,642.256000,972.768000,3.344000,3.856000,4.752000,2.424000,3.000000,912.480000
Steve Hawthorne,944.200000,513.600000,969.066667,6.000000,3.900000,3.200000,2.600000,3.000000,914.000000
Clayton Schuster,871.400000,1232.800000,967.266667,5.000000,3.600000,4.200000,2.600000,3.000000,748.000000
Philip Priddy,929.070833,760.945833,964.887500,3.875000,3.866667,4.408333,2.400000,3.000000,976.083333
Natalie Mika,792.750000,529.250000,964.250000,7.750000,3.250000,1.750000,2.750000,3.500000,987.000000
John Tracey,941.604167,736.220833,960.565278,3.195833,3.912500,4.725000,2.429167,3.000000,981.062500
Harry Franklin,933.420000,1030.600000,960.160000,4.160000,3.900000,4.560000,2.540000,3.000000,1171.200000
Cary Carmichael,940.469767,735.237209,957.034109,3.320930,3.930233,4.744186,2.488372,3.000000,981.116279
"""Cody""",771.200000,1116.200000,949.866667,4.800000,3.200000,2.800000,2.000000,3.000000,748.000000
Filimon Garcia,794.333333,971.800000,944.355556,6.666667,3.400000,2.400000,2.333333,3.000000,976.000000
Jesus Tarango,942.000000,992.400000,942.000000,7.800000,4.000000,4.200000,2.200000,3.000000,987.000000
...,...,...,...,...,...,...,...,...,...
Sarai Rodriguez,817.600000,388.600000,817.600000,2.800000,4.000000,3.400000,2.400000,3.000000,861.000000
Keenan White,791.200000,747.000000,816.566667,6.200000,3.900000,3.100000,2.600000,3.000000,987.000000
Julie Gomez,816.200000,770.200000,816.200000,5.400000,4.000000,2.200000,2.600000,3.000000,1080.000000
William E Rubley,815.800000,493.400000,815.800000,2.400000,4.000000,4.200000,3.600000,3.000000,987.000000
Jason Garcia,797.307692,772.461538,815.466667,4.615385,3.892308,3.923077,2.461538,3.000000,1141.384615
Cody Reeves,754.560000,569.120000,815.146667,4.600000,3.680000,3.280000,2.440000,3.000000,748.000000
Lee Loftin,801.444444,746.866667,811.992593,3.555556,3.955556,3.955556,2.422222,3.000000,821.777778
Tally McTrees,811.200000,993.600000,811.200000,7.800000,4.000000,2.600000,3.400000,3.000000,987.000000
Presley Lippert,693.800000,651.200000,810.133333,7.600000,3.400000,1.000000,3.000000,3.000000,861.000000
Barrett Lindstrom,768.388889,751.522222,808.337037,5.255556,3.811111,3.566667,2.577778,3.000000,1080.666667
Nico Cerna,781.800000,784.600000,807.166667,5.000000,3.866667,3.500000,2.266667,3.000000,877.500000
Vincent Ruggiero,789.177778,853.977778,797.874074,4.866667,3.933333,3.622222,2.511111,3.000000,1194.000000
Steven Thomas Jr.,710.945055,746.043956,794.560440,5.945055,3.582418,3.065934,2.153846,3.043956,977.219780
Steve Samuels,790.600000,1333.800000,790.600000,6.600000,4.000000,3.000000,1.400000,3.000000,1080.000000
Ryan Walters,788.400000,988.800000,788.400000,6.800000,4.000000,2.600000,2.600000,3.000000,987.000000
Chris Stark,727.100000,574.300000,784.466667,4.500000,3.700000,4.100000,2.500000,3.000000,1027.500000
Neil McRae,771.800000,576.600000,771.800000,3.400000,4.000000,5.000000,1.800000,3.000000,748.000000
Isaak Cervantes,729.960000,739.800000,771.693333,4.360000,3.800000,3.680000,2.480000,3.000000,814.400000
CIPI3,748.600000,504.250000,770.150000,5.000000,3.900000,3.700000,2.100000,3.000000,1080.000000
Madison Garcia,766.285714,819.571429,766.285714,4.571429,4.000000,2.428571,1.571429,2.571429,923.571429
Joseph Jacobs,719.000000,645.400000,760.466667,6.200000,3.800000,4.000000,2.200000,3.000000,861.000000
Dan Bryant,725.200000,96.400000,760.133333,5.800000,3.800000,3.800000,2.200000,3.000000,1194.000000
Sage Fleming,725.000000,187.800000,757.866667,3.800000,3.800000,3.800000,2.600000,3.000000,987.000000
Caitlin O'Driscoll,746.200000,990.200000,746.200000,7.200000,4.000000,3.400000,2.400000,3.000000,987.000000
Christina Jones,558.600000,718.000000,744.800000,5.400000,3.000000,3.400000,1.800000,3.000000,748.000000
Kris Lippert,741.000000,642.400000,741.000000,5.200000,4.000000,3.000000,3.200000,3.000000,861.000000
Katie Donotdareputmeinthis,675.100000,492.800000,737.683333,5.250000,3.650000,3.900000,2.350000,3.000000,832.750000
DJ Shea,680.800000,498.200000,680.800000,3.800000,4.000000,3.400000,2.800000,3.000000,987.000000
Angel Reyes,640.800000,192.800000,668.933333,5.000000,3.800000,3.400000,2.800000,3.000000,987.000000
Ben McDowell,623.400000,986.000000,623.400000,6.000000,4.000000,3.800000,3.000000,3.000000,987.000000

In [11]:
df.groupby(['players','num_players']).mean()

                                        Time   Unnamed: 0     adj_time  \
players             num_players
"Andrea"            4            1078.200000   607.400000  1078.200000
"Blaise"            4             834.600000   977.200000   834.600000
"Cody"              3             670.000000  1118.000000   893.333333
                    4            1176.000000  1109.000000  1176.000000
"Penelope"          3             618.200000  1118.400000   824.266667
Aalono Steck        3             766.000000   810.500000  1021.333333
                    4             983.000000   759.000000   983.000000
Aaron Rossi         4             825.800000   552.800000   825.800000
Adam Venuti         4             840.200000   640.600000   840.200000
Alejandro Rodriguez 4             884.000000   195.000000   884.000000
Alex Rodriguez      3             658.250000  1233.750000   877.666667
                    4             746.000000  1145.000000   746.000000
Anders Lindström US 3             605.600000   547.666667   807.466667
                    4             877.633333   780.183333   877.633333
Andrew Gomez        4             847.600000   772.200000   847.600000
Angel Reyes         3             422.000000   234.000000   562.666667
                    4             695.500000   182.500000   695.500000
Anthony Garcia CA   3             683.172414   817.517241   910.896552
                    4             875.171171   893.315315   875.171171
Barrett Lindstrom   3             634.470588  1091.941176   845.960784
                    4             799.575342   672.246575   799.575342
BeeOtch Westrum     3             682.219512  1021.926829   909.626016
                    4             911.000000   740.522388   911.000000
Ben McDowell        4             623.400000   986.000000   623.400000
Big Boi             4             918.400000   989.800000   918.400000
Breanna Lane        3             810.250000   972.000000  1080.333333
                    4             714.000000   873.000000   714.000000
Brian Ebach         3             646.000000  1535.000000   861.333333
                    4             876.000000  1525.500000   876.000000
Brianna Johnson     3             661.000000    58.285714   881.333333
...                                      ...          ...          ...
Steve Hawthorne     4             966.222222   456.666667   966.222222
Steve Samuels       4             790.600000  1333.800000   790.600000
Steven R Thomas     3             695.333333   708.974359   927.111111
                    4             890.038462   702.192308   890.038462
Steven Thomas Jr.   3             600.710526   681.763158   800.947368
                    4             789.981132   792.132075   789.981132
Tally McTrees       4             811.200000   993.600000   811.200000
Tara Seagal         4             842.200000   602.600000   842.200000
Tasha Lindstrom     3             681.333333   792.750000   908.444444
                    4             887.470588   682.897059   887.470588
Todd Brammer        3             787.000000   932.058824  1049.333333
                    4             982.096386   817.674699   982.096386
Tony Lavigna        3             750.666667  1161.833333  1000.888889
                    4             936.245614   844.315789   936.245614
Tyler Heath         3             621.400000   960.033333   828.533333
                    4             910.166667   714.709524   910.166667
Vincent Ruggiero    3             391.333333   784.666667   521.777778
                    4             817.595238   858.928571   817.595238
Whitney Clark       3             577.250000   783.666667   769.666667
                    4             846.173913   631.869565   846.173913
Will Chernetsky     3             634.588235   667.823529   846.117647
                    4             867.583333   741.527778   867.583333
William E Rubley    4             815.800000   493.400000   815.800000
Xavier Marin        4             874.000000   678.000000   874.000000
Zack Stephens       3             862.333333   503.666667  1149.777778
                    4             926.000000   625.333333   926.000000
“Iris”              3             588.771429   689.942857   785.028571
                    4             917.227273   740.000000   917.227273
“RC”                3             650.826087   676.173913   867.768116
                    4             872.247863   713.230769   872.247863

                                 group_number    points  positions  \
players             num_players
"Andrea"            4                7.800000  1.400000   2.200000
"Blaise"            4                3.400000  4.200000   2.600000
"Cody"              3                5.250000  3.250000   2.250000
                    4                3.000000  1.000000   1.000000
"Penelope"          3                5.600000  1.000000   1.600000
Aalono Steck        3                7.000000  2.500000   2.000000
                    4                5.000000  1.000000   1.000000
Aaron Rossi         4                4.800000  2.600000   2.200000
Adam Venuti         4                5.000000  2.600000   2.200000
Alejandro Rodriguez 4                5.600000  3.000000   2.600000
Alex Rodriguez      3                6.750000  3.250000   2.000000
                    4                2.000000  1.000000   3.000000
Anders Lindström US 3                8.133333  2.600000   1.800000
                    4                5.950000  3.166667   2.416667
Andrew Gomez        4                6.000000  3.400000   2.200000
Angel Reyes         3                7.000000  7.000000   3.000000
                    4                4.500000  2.500000   2.750000
Anthony Garcia CA   3                8.275862  3.275862   2.000000
                    4                4.549550  3.360360   2.684685
Barrett Lindstrom   3                8.294118  4.000000   2.411765
                    4                4.547945  3.465753   2.616438
BeeOtch Westrum     3                7.634146  4.365854   2.073171
                    4                4.410448  3.626866   2.537313
Ben McDowell        4                6.000000  3.800000   3.000000
Big Boi             4                7.000000  3.000000   2.800000
Breanna Lane        3                9.500000  4.000000   2.000000
                    4                7.000000  1.000000   3.000000
Brian Ebach         3                9.000000  7.000000   2.000000
                    4                6.000000  1.500000   3.500000
Brianna Johnson     3                6.428571  2.714286   1.714286
...                                       ...       ...        ...
Steve Hawthorne     4                5.666667  2.777778   2.666667
Steve Samuels       4                6.600000  3.000000   1.400000
Steven R Thomas     3                6.641026  4.538462   1.743590
                    4                3.972527  3.670330   2.500000
Steven Thomas Jr.   3                7.421053  3.368421   2.052632
                    4                4.886792  2.849057   2.226415
Tally McTrees       4                7.800000  2.600000   3.400000
Tara Seagal         4                6.600000  3.000000   2.200000
Tasha Lindstrom     3                8.583333  3.750000   2.000000
                    4                4.852941  3.676471   2.235294
Todd Brammer        3                8.235294  3.470588   2.176471
                    4                4.204819  3.795181   2.481928
Tony Lavigna        3                8.166667  5.000000   1.833333
                    4                2.956140  4.964912   2.570175
Tyler Heath         3                6.566667  4.400000   2.066667
                    4                3.752381  4.057143   2.571429
Vincent Ruggiero    3                9.000000  3.000000   2.333333
                    4                4.571429  3.666667   2.523810
Whitney Clark       3                8.583333  3.250000   1.833333
                    4                5.391304  2.565217   2.434783
Will Chernetsky     3                6.647059  4.617647   2.088235
                    4                3.097222  4.648148   2.398148
William E Rubley    4                2.400000  4.200000   3.600000
Xavier Marin        4                4.100000  4.800000   1.600000
Zack Stephens       3                8.666667  4.000000   2.000000
                    4                4.000000  2.333333   3.333333
“Iris”              3                7.400000  3.400000   1.885714
                    4                4.036364  3.490909   2.509091
“RC”                3                7.130435  4.260870   2.260870
                    4                3.521368  4.264957   2.452991

                                 round_number    season_id
players             num_players
"Andrea"            4                3.000000  1080.000000
"Blaise"            4                3.000000   748.000000
"Cody"              3                3.000000   748.000000
                    4                3.000000   748.000000
"Penelope"          3                3.000000   748.000000
Aalono Steck        3                2.500000   987.000000
                    4                1.000000   987.000000
Aaron Rossi         4                3.000000  1194.000000
Adam Venuti         4                3.000000   861.000000
Alejandro Rodriguez 4                3.000000   987.000000
Alex Rodriguez      3                3.500000   861.000000
                    4                1.000000   861.000000
Anders Lindström US 3                3.066667  1062.200000
                    4                2.983333  1093.200000
Andrew Gomez        4                3.000000  1080.000000
Angel Reyes         3                4.000000   987.000000
                    4                2.750000   987.000000
Anthony Garcia CA   3                3.241379  1026.517241
                    4                2.936937  1092.621622
Barrett Lindstrom   3                3.117647  1080.705882
                    4                2.972603  1080.657534
BeeOtch Westrum     3                2.902439  1047.585366
                    4                3.029851  1048.723881
Ben McDowell        4                3.000000   987.000000
Big Boi             4                3.000000   987.000000
Breanna Lane        3                3.500000  1080.000000
                    4                1.000000  1080.000000
Brian Ebach         3                3.000000  1080.000000
                    4                3.000000  1080.000000
Brianna Johnson     3                2.571429   926.571429
...                                       ...          ...
Steve Hawthorne     4                2.777778   895.555556
Steve Samuels       4                3.000000  1080.000000
Steven R Thomas     3                2.871795   939.794872
                    4                3.043956   967.208791
Steven Thomas Jr.   3                3.210526   970.500000
                    4                2.924528   982.037736
Tally McTrees       4                3.000000   987.000000
Tara Seagal         4                3.000000  1080.000000
Tasha Lindstrom     3                3.000000  1100.750000
                    4                3.000000  1084.058824
Todd Brammer        3                2.705882  1061.117647
                    4                3.060241  1028.144578
Tony Lavigna        3                1.833333  1007.333333
                    4                3.061404   963.210526
Tyler Heath         3                2.866667   954.533333
                    4                3.019048   976.923810
Vincent Ruggiero    3                1.000000  1194.000000
                    4                3.142857  1194.000000
Whitney Clark       3                3.333333  1194.000000
                    4                2.826087  1194.000000
Will Chernetsky     3                2.470588   916.617647
                    4                3.083333   983.032407
William E Rubley    4                3.000000   987.000000
Xavier Marin        4                3.000000  1080.000000
Zack Stephens       3                3.666667  1018.000000
                    4                2.000000   987.000000
“Iris”              3                3.114286   882.514286
                    4                2.963636   919.200000
“RC”                3                2.826087   939.391304
                    4                3.034188   911.572650

[263 rows x 8 columns]

In [12]:
df.groupby(['Arena','positions']).mean()

                                                    Time   Unnamed: 0  \
Arena                             positions
2001                              1           718.590909   741.181818
                                  2           718.590909   742.181818
                                  3           718.590909   743.181818
                                  4           760.960000   707.080000
Attack From Mars                  1           791.904762   780.428571
                                  2           791.904762   781.428571
                                  3           791.904762   782.428571
                                  4           808.884615   780.865385
Batman Dark Knight                1           825.500000   605.846154
                                  2           825.500000   606.846154
                                  3           825.500000   607.846154
                                  4           902.150000   676.700000
Baywatch                          1          1058.842105   594.263158
                                  2          1058.842105   595.263158
                                  3          1058.842105   596.263158
                                  4          1114.687500   511.437500
Beatles                           1           915.500000   222.500000
                                  2           915.500000   223.500000
                                  3           915.500000   224.500000
                                  4          1004.000000   199.000000
Big Buck Hunter                   1           709.416667   844.666667
                                  2           709.416667   845.666667
                                  3           709.416667   846.666667
                                  4           764.000000   853.888889
Bram Stokers Dracula              1           789.285714  1212.142857
                                  2           789.285714  1213.142857
                                  3           789.285714  1214.142857
                                  4           890.400000  1251.400000
Bride of Pinbot 2.0               1           845.000000   156.000000
                                  2           845.000000   157.000000
...                                                  ...          ...
The Wizard of Oz (LE)             2           690.000000  1176.000000
                                  3           690.000000  1177.000000
The Wizard of Oz Emerald City LE  1           878.000000   869.000000
                                  2           878.000000   870.000000
                                  3           878.000000   871.000000
                                  4           878.000000   872.000000
Total Nuclear Annihilation        1           842.938462   784.953846
                                  2           842.938462   785.953846
                                  3           842.938462   786.953846
                                  4           882.423077   787.846154
Tron                              1           876.160000   584.600000
                                  2           876.160000   585.600000
                                  3           876.160000   586.600000
                                  4           908.190476   571.523810
WWF Royal Rumble                  1           806.000000   402.615385
                                  2           806.000000   403.615385
                                  3           806.000000   404.615385
                                  4           857.000000   350.888889
White Water                       1           997.272727   692.954545
                                  2           997.272727   693.954545
                                  3           997.272727   694.954545
                                  4          1074.437500   738.687500
World Cup Soccer                  1           757.757576   733.424242
                                  2           757.757576   734.424242
                                  3           757.757576   735.424242
                                  4           796.945455   766.672727
X-Men                             1          1147.578947   676.394737
                                  2          1147.578947   677.394737
                                  3          1147.578947   678.394737
                                  4          1227.724138   706.931034

                                                adj_time  group_number  \
Arena                             positions
2001                              1           765.959596      4.560606
                                  2           765.959596      4.560606
                                  3           765.959596      4.560606
                                  4           760.960000      3.640000
Attack From Mars                  1           833.322751      4.444444
                                  2           833.322751      4.444444
                                  3           833.322751      4.444444
                                  4           808.884615      3.942308
Batman Dark Knight                1           869.346154      4.423077
                                  2           869.346154      4.423077
                                  3           869.346154      4.423077
                                  4           902.150000      3.950000
Baywatch                          1          1098.894737      4.526316
                                  2          1098.894737      4.526316
                                  3          1098.894737      4.526316
                                  4          1114.687500      4.187500
Beatles                           1          1053.333333      3.250000
                                  2          1053.333333      3.250000
                                  3          1053.333333      3.250000
                                  4          1004.000000      1.500000
Big Buck Hunter                   1           754.888889      4.708333
                                  2           754.888889      4.708333
                                  3           754.888889      4.708333
                                  4           764.000000      3.944444
Bram Stokers Dracula              1           840.380952      5.000000
                                  2           840.380952      5.000000
                                  3           840.380952      5.000000
                                  4           890.400000      3.800000
Bride of Pinbot 2.0               1           845.000000      8.000000
                                  2           845.000000      8.000000
...                                                  ...           ...
The Wizard of Oz (LE)             2           920.000000      5.000000
                                  3           920.000000      5.000000
The Wizard of Oz Emerald City LE  1           878.000000      4.000000
                                  2           878.000000      4.000000
                                  3           878.000000      4.000000
                                  4           878.000000      4.000000
Total Nuclear Annihilation        1           888.605128      4.538462
                                  2           888.605128      4.538462
                                  3           888.605128      4.538462
                                  4           882.423077      3.865385
Tron                              1           913.920000      4.080000
                                  2           913.920000      4.080000
                                  3           913.920000      4.080000
                                  4           908.190476      3.619048
WWF Royal Rumble                  1           876.897436      4.153846
                                  2           876.897436      4.153846
                                  3           876.897436      4.153846
                                  4           857.000000      3.666667
White Water                       1          1069.227273      4.818182
                                  2          1069.227273      4.818182
                                  3          1069.227273      4.818182
                                  4          1074.437500      4.250000
World Cup Soccer                  1           788.969697      4.287879
                                  2           788.969697      4.287879
                                  3           788.969697      4.287879
                                  4           796.945455      3.727273
X-Men                             1          1217.789474      4.263158
                                  2          1217.789474      4.263158
                                  3          1217.789474      4.263158
                                  4          1227.724138      3.551724

                                             num_players    points  \
Arena                             positions
2001                              1             3.757576  4.196970
                                  2             3.757576  3.893939
                                  3             3.757576  3.939394
                                  4             4.000000  3.960000
Attack From Mars                  1             3.825397  4.301587
                                  2             3.825397  4.238095
                                  3             3.825397  4.095238
                                  4             4.000000  3.230769
Batman Dark Knight                1             3.769231  4.346154
                                  2             3.769231  4.115385
                                  3             3.769231  3.307692
                                  4             4.000000  4.300000
Baywatch                          1             3.842105  4.263158
                                  2             3.842105  4.421053
                                  3             3.842105  3.315789
                                  4             4.000000  4.000000
Beatles                           1             3.500000  3.500000
                                  2             3.500000  3.750000
                                  3             3.500000  5.250000
                                  4             4.000000  3.000000
Big Buck Hunter                   1             3.750000  3.875000
                                  2             3.750000  4.333333
                                  3             3.750000  3.541667
                                  4             4.000000  4.333333
Bram Stokers Dracula              1             3.714286  4.142857
                                  2             3.714286  2.285714
                                  3             3.714286  5.714286
                                  4             4.000000  3.800000
Bride of Pinbot 2.0               1             4.000000  3.000000
                                  2             4.000000  5.000000
...                                                  ...       ...
The Wizard of Oz (LE)             2             3.000000  1.000000
                                  3             3.000000  7.000000
The Wizard of Oz Emerald City LE  1             4.000000  7.000000
                                  2             4.000000  3.000000
                                  3             4.000000  1.000000
                                  4             4.000000  5.000000
Total Nuclear Annihilation        1             3.800000  3.969231
                                  2             3.800000  4.092308
                                  3             3.800000  3.569231
                                  4             4.000000  4.461538
Tron                              1             3.840000  3.480000
                                  2             3.840000  3.640000
                                  3             3.840000  4.520000
                                  4             4.000000  4.428571
WWF Royal Rumble                  1             3.692308  4.153846
                                  2             3.692308  4.153846
                                  3             3.692308  4.230769
                                  4             4.000000  3.222222
White Water                       1             3.727273  3.636364
                                  2             3.727273  3.545455
                                  3             3.727273  5.090909
                                  4             4.000000  3.625000
World Cup Soccer                  1             3.833333  4.560606
                                  2             3.833333  3.742424
                                  3             3.833333  3.984848
                                  4             4.000000  3.654545
X-Men                             1             3.763158  5.000000
                                  2             3.763158  3.578947
                                  3             3.763158  3.447368
                                  4             4.000000  3.965517

                                             round_number    season_id
Arena                             positions
2001                              1              3.151515  1033.409091
                                  2              3.151515  1033.409091
                                  3              3.151515  1033.409091
                                  4              3.200000  1043.240000
Attack From Mars                  1              3.126984   932.793651
                                  2              3.126984   932.793651
                                  3              3.126984   932.793651
                                  4              3.230769   932.384615
Batman Dark Knight                1              2.923077   902.807692
                                  2              2.923077   902.807692
                                  3              2.923077   902.807692
                                  4              2.950000   908.400000
Baywatch                          1              2.789474   928.315789
                                  2              2.789474   928.315789
                                  3              2.789474   928.315789
                                  4              2.750000   932.250000
Beatles                           1              3.250000   861.000000
                                  2              3.250000   861.000000
                                  3              3.250000   861.000000
                                  4              2.500000   861.000000
Big Buck Hunter                   1              3.125000  1017.583333
                                  2              3.125000  1017.583333
                                  3              3.125000  1017.583333
                                  4              3.166667  1051.611111
Bram Stokers Dracula              1              3.000000  1194.000000
                                  2              3.000000  1194.000000
                                  3              3.000000  1194.000000
                                  4              3.200000  1194.000000
Bride of Pinbot 2.0               1              5.000000   748.000000
                                  2              5.000000   748.000000
...                                                   ...          ...
The Wizard of Oz (LE)             2              4.000000   987.000000
                                  3              4.000000   987.000000
The Wizard of Oz Emerald City LE  1              5.000000   987.000000
                                  2              5.000000   987.000000
                                  3              5.000000   987.000000
                                  4              5.000000   987.000000
Total Nuclear Annihilation        1              3.169231   981.369231
                                  2              3.169231   981.369231
                                  3              3.169231   981.369231
                                  4              3.250000   994.096154
Tron                              1              3.400000   784.160000
                                  2              3.400000   784.160000
                                  3              3.400000   784.160000
                                  4              3.238095   791.047619
WWF Royal Rumble                  1              2.923077   748.000000
                                  2              2.923077   748.000000
                                  3              2.923077   748.000000
                                  4              2.555556   748.000000
White Water                       1              3.454545   948.727273
                                  2              3.454545   948.727273
                                  3              3.454545   948.727273
                                  4              3.500000   965.875000
World Cup Soccer                  1              2.954545  1020.742424
                                  2              2.954545  1020.742424
                                  3              2.954545  1020.742424
                                  4              2.909091  1034.218182
X-Men                             1              3.210526   898.289474
                                  2              3.210526   898.289474
                                  3              3.210526   898.289474
                                  4              3.275862   896.379310

[274 rows x 8 columns]

In [13]:
df.groupby(['group_number','round_number']).count()

                           Arena  Time  Unnamed: 0  adj_time  num_players  \
group_number round_number
1            1               200   200         200       200          200
             2               200   200         200       200          200
             3               200   200         200       200          200
             4               200   200         200       200          200
             5               200   200         200       200          200
2            1               200   200         200       200          200
             2               200   200         200       200          200
             3               200   200         200       200          200
             4               200   200         200       200          200
             5               200   200         200       200          200
3            1               200   200         200       200          200
             2               200   200         200       200          200
             3               200   200         200       200          200
             4               200   200         200       200          200
             5               200   200         200       200          200
4            1               195   195         195       195          195
             2               196   196         196       196          196
             3               196   196         196       196          196
             4               196   196         196       196          196
             5               196   196         196       196          196
5            1               189   189         189       189          189
             2               189   189         189       189          189
             3               188   188         188       188          188
             4               189   189         189       189          189
             5               189   189         189       189          189
6            1               179   179         179       179          179
             2               177   177         177       177          177
             3               177   177         177       177          177
             4               178   178         178       178          178
             5               181   181         181       181          181
7            1               139   139         139       139          139
             2               144   144         144       144          144
             3               143   143         143       143          143
             4               142   142         142       142          142
             5               142   142         142       142          142
8            1               103   103         103       103          103
             2               105   105         105       105          105
             3               108   108         108       108          108
             4               105   105         105       105          105
             5               105   105         105       105          105
9            1                52    52          52        52           52
             2                54    54          54        54           54
             3                51    51          51        51           51
             4                51    51          51        51           51
             5                52    52          52        52           52
10           1                16    16          16        16           16
             2                19    19          19        19           19
             3                20    20          20        20           20
             4                20    20          20        20           20
             5                20    20          20        20           20
11           1                 3     3           3         3            3
             2                 3     3           3         3            3
             3                 3     3           3         3            3
             4                 3     3           3         3            3
             5                 3     3           3         3            3

                           places  players  points  positions  season_id
group_number round_number
1            1                200      200     200        200        200
             2                200      200     200        200        200
             3                200      200     200        200        200
             4                200      200     200        200        200
             5                200      200     200        200        200
2            1                200      200     200        200        200
             2                200      200     200        200        200
             3                200      200     200        200        200
             4                200      200     200        200        200
             5                200      200     200        200        200
3            1                200      200     200        200        200
             2                200      200     200        200        200
             3                200      200     200        200        200
             4                200      200     200        200        200
             5                200      200     200        200        200
4            1                195      195     195        195        195
             2                196      196     196        196        196
             3                196      196     196        196        196
             4                196      196     196        196        196
             5                196      196     196        196        196
5            1                189      189     189        189        189
             2                189      189     189        189        189
             3                188      188     188        188        188
             4                189      189     189        189        189
             5                189      189     189        189        189
6            1                179      179     179        179        179
             2                177      177     177        177        177
             3                177      177     177        177        177
             4                178      178     178        178        178
             5                181      181     181        181        181
7            1                139      139     139        139        139
             2                144      144     144        144        144
             3                143      143     143        143        143
             4                142      142     142        142        142
             5                142      142     142        142        142
8            1                103      103     103        103        103
             2                105      105     105        105        105
             3                108      108     108        108        108
             4                105      105     105        105        105
             5                105      105     105        105        105
9            1                 52       52      52         52         52
             2                 54       54      54         54         54
             3                 51       51      51         51         51
             4                 51       51      51         51         51
             5                 52       52      52         52         52
10           1                 16       16      16         16         16
             2                 19       19      19         19         19
             3                 20       20      20         20         20
             4                 20       20      20         20         20
             5                 20       20      20         20         20
11           1                  3        3       3          3          3
             2                  3        3       3          3          3
             3                  3        3       3          3          3
             4                  3        3       3          3          3
             5                  3        3       3          3          3

In [14]:
df.groupby(['players','positions']).mean()

                                      Time   Unnamed: 0     adj_time  \
players             positions
"Andrea"            1           869.000000   621.666667   869.000000
                    4          1392.000000   586.000000  1392.000000
"Blaise"            1           670.500000  1011.000000   670.500000
                    3           760.000000   910.000000   760.000000
                    4          1036.000000   977.000000  1036.000000
"Cody"              1           984.000000  1091.500000  1116.000000
                    2           743.000000  1138.000000   990.666667
                    3           572.500000  1130.000000   763.333333
"Penelope"          1           561.333333  1124.000000   748.444444
                    2          1030.000000  1099.000000  1373.333333
                    3           377.000000  1121.000000   502.666667
Aalono Steck        1           983.000000   759.000000   983.000000
                    2           766.000000   810.500000  1021.333333
Aaron Rossi         1           791.000000   571.000000   791.000000
                    2           836.000000   489.000000   836.000000
                    3           903.000000   579.000000   903.000000
                    4           808.000000   554.000000   808.000000
Adam Venuti         1           826.000000   658.000000   826.000000
                    2           796.000000   636.000000   796.000000
                    3           882.000000   567.000000   882.000000
                    4           871.000000   684.000000   871.000000
Alejandro Rodriguez 1           985.000000   261.000000   985.000000
                    2           724.000000   229.000000   724.000000
                    3           716.500000   160.000000   716.500000
                    4          1278.000000   165.000000  1278.000000
Alex Rodriguez      1           703.000000  1219.000000   937.333333
                    3           657.666667  1214.000000   794.000000
Anders Lindström US 1           795.913043   771.478261   850.710145
                    2           843.380952   651.047619   900.158730
                    3           846.529412   742.941176   880.372549
...                                    ...          ...          ...
Tyler Heath         2           842.236111   862.458333   901.837963
                    3           888.114754   778.213115   908.377049
                    4           912.214286   597.607143   912.214286
Vincent Ruggiero    1           819.666667   811.166667   829.666667
                    2           820.000000   880.777778   820.000000
                    3           714.923077   871.461538   735.794872
                    4           818.454545   858.090909   818.454545
Whitney Clark       1           740.818182   669.000000   828.000000
                    2           827.600000   703.900000   912.033333
                    3           689.111111   692.666667   745.296296
                    4           752.400000   661.000000   752.400000
Will Chernetsky     1           840.876923   742.353846   874.676923
                    2           842.701299   618.714286   872.593074
                    3           797.000000   812.677419   840.440860
                    4           869.891304   795.565217   869.891304
William E Rubley    3           874.000000   479.500000   874.000000
                    4           777.000000   502.666667   777.000000
Xavier Marin        1           838.500000   693.666667   838.500000
                    2           942.500000   560.000000   942.500000
                    3           912.000000   749.000000   912.000000
Zack Stephens       2           854.750000   544.000000  1070.333333
                    4           973.000000   605.500000   973.000000
“Iris”              1           852.000000   735.450000   916.208333
                    2           782.054054   721.081081   847.252252
                    3           855.386364   691.227273   898.303030
                    4           868.708333   793.166667   868.708333
“RC”                1           887.800000   769.566667   908.433333
                    2           848.550000   709.475000   913.766667
                    3           809.725490   665.392157   844.274510
                    4           797.368421   715.736842   797.368421

                               group_number  num_players    points  \
players             positions
"Andrea"            1              8.666667     4.000000  1.666667
                    4              6.500000     4.000000  1.000000
"Blaise"            1              4.500000     4.000000  4.000000
                    3              2.000000     4.000000  7.000000
                    4              3.000000     4.000000  3.000000
"Cody"              1              4.000000     3.500000  1.000000
                    2              5.000000     3.000000  1.000000
                    3              5.500000     3.000000  5.500000
"Penelope"          1              5.333333     3.000000  1.000000
                    2              6.000000     3.000000  1.000000
                    3              6.000000     3.000000  1.000000
Aalono Steck        1              5.000000     4.000000  1.000000
                    2              7.000000     3.000000  2.500000
Aaron Rossi         1              6.000000     4.000000  3.000000
                    2              3.000000     4.000000  1.000000
                    3              4.000000     4.000000  1.000000
                    4              5.000000     4.000000  5.000000
Adam Venuti         1              5.500000     4.000000  2.000000
                    2              4.000000     4.000000  1.000000
                    3              3.000000     4.000000  5.000000
                    4              7.000000     4.000000  3.000000
Alejandro Rodriguez 1              6.000000     4.000000  1.000000
                    2              6.000000     4.000000  5.000000
                    3              5.000000     4.000000  2.000000
                    4              6.000000     4.000000  5.000000
Alex Rodriguez      1              7.000000     3.000000  4.000000
                    3              5.000000     3.333333  2.000000
Anders Lindström US 1              6.826087     3.739130  3.000000
                    2              6.476190     3.714286  2.952381
                    3              6.529412     3.823529  3.058824
...                                     ...          ...       ...
Tyler Heath         2              4.541667     3.722222  4.333333
                    3              4.114754     3.901639  3.721311
                    4              3.285714     4.000000  4.071429
Vincent Ruggiero    1              4.583333     3.916667  4.250000
                    2              5.000000     4.000000  3.888889
                    3              5.384615     3.846154  3.076923
                    4              4.454545     4.000000  3.363636
Whitney Clark       1              6.818182     3.545455  3.454545
                    2              6.200000     3.600000  2.000000
                    3              6.555556     3.666667  3.000000
                    4              6.200000     4.000000  2.600000
Will Chernetsky     1              3.738462     3.846154  4.846154
                    2              3.493506     3.857143  4.623377
                    3              3.838710     3.790323  4.580645
                    4              3.152174     4.000000  4.478261
William E Rubley    3              3.000000     4.000000  3.000000
                    4              2.000000     4.000000  5.000000
Xavier Marin        1              3.833333     4.000000  5.333333
                    2              5.000000     4.000000  4.000000
                    3              4.000000     4.000000  4.000000
Zack Stephens       2              8.000000     3.250000  3.250000
                    4              3.000000     4.000000  3.000000
“Iris”              1              5.375000     3.675000  3.875000
                    2              4.432432     3.648649  3.513514
                    3              5.113636     3.795455  3.136364
                    4              4.125000     4.000000  3.333333
“RC”                1              3.200000     3.900000  4.133333
                    2              4.650000     3.725000  4.425000
                    3              4.313725     3.823529  4.137255
                    4              3.894737     4.000000  4.473684

                               round_number    season_id
players             positions
"Andrea"            1              3.333333  1080.000000
                    4              2.500000  1080.000000
"Blaise"            1              4.000000   748.000000
                    3              1.000000   748.000000
                    4              3.000000   748.000000
"Cody"              1              2.000000   748.000000
                    2              4.000000   748.000000
                    3              3.500000   748.000000
"Penelope"          1              3.333333   748.000000
                    2              2.000000   748.000000
                    3              3.000000   748.000000
Aalono Steck        1              1.000000   987.000000
                    2              2.500000   987.000000
Aaron Rossi         1              3.500000  1194.000000
                    2              1.000000  1194.000000
                    3              4.000000  1194.000000
                    4              3.000000  1194.000000
Adam Venuti         1              3.500000   861.000000
                    2              3.000000   861.000000
                    3              1.000000   861.000000
                    4              4.000000   861.000000
Alejandro Rodriguez 1              5.000000   987.000000
                    2              4.000000   987.000000
                    3              2.000000   987.000000
                    4              2.000000   987.000000
Alex Rodriguez      1              3.000000   861.000000
                    3              3.000000   861.000000
Anders Lindström US 1              3.304348  1090.434783
                    2              2.952381  1062.857143
                    3              2.882353  1111.764706
...                                     ...          ...
Tyler Heath         2              2.986111   986.986111
                    3              3.196721   986.491803
                    4              2.803571   958.339286
Vincent Ruggiero    1              2.916667  1194.000000
                    2              3.777778  1194.000000
                    3              2.692308  1194.000000
                    4              2.818182  1194.000000
Whitney Clark       1              2.818182  1194.000000
                    2              2.700000  1194.000000
                    3              3.555556  1194.000000
                    4              3.000000  1194.000000
Will Chernetsky     1              3.000000   977.907692
                    2              2.948052   963.545455
                    3              2.838710   981.790323
                    4              3.304348   975.478261
William E Rubley    3              2.500000   987.000000
                    4              3.333333   987.000000
Xavier Marin        1              3.500000  1080.000000
                    2              2.000000  1080.000000
                    3              2.500000  1080.000000
Zack Stephens       2              3.500000  1010.250000
                    4              1.500000   987.000000
“Iris”              1              3.200000   951.350000
                    2              2.864865   864.837838
                    3              2.931818   903.590909
                    4              3.000000   924.541667
“RC”                1              3.233333   902.933333
                    2              3.050000   942.050000
                    3              2.705882   907.509804
                    4              3.315789   905.631579

[525 rows x 8 columns]

In [15]:
df.groupby('round_number').mean()

,Time,Unnamed: 0,adj_time,group_number,num_players,points,positions,season_id
round_number,,,,,,,,
1,830.308266,692.491870,865.756098,4.374661,3.837398,4.0,2.418699,991.096206
2,871.746469,720.989240,909.194351,4.403497,3.836584,4.0,2.418292,991.416274
3,861.143338,753.799462,897.921938,4.403096,3.834455,4.0,2.417227,991.586810
4,856.041105,784.515499,891.051213,4.395553,3.838275,4.0,2.419137,991.592992
5,868.647177,815.472446,905.139785,4.401882,3.838710,4.0,2.419355,991.473790

In [16]:
group_round_times = df.groupby(['round_number','group_number']).mean().reset_index()
data = [
    go.Heatmap(
        x=group_round_times['round_number'],
        y=group_round_times['group_number'],
        z=group_round_times['adj_time']
    )
]
layout = go.Layout(
    yaxis=dict(
        autorange='reversed'
    )
)
fig = go.Figure(data=data, layout=layout)
py.iplot(fig, filename='round-group-time-heatmap')