In [63]:
from bs4 import BeautifulSoup
import pandas as pd

In [64]:
f = open('ipdb-alpha-game-list.html', 'r')
page = f.read()
f.close()

In [65]:
soup = BeautifulSoup(page)

In [66]:
table = soup.find_all('table')[0]

In [80]:
df = pd.read_html(str(table),header=0)[0]

In [81]:
df.dropna(inplace=True)

In [82]:
df['Date Manufactured'] = pd.to_datetime(df['Date Manufactured'])

In [83]:
df = df[df['Date Manufactured'] >= '1960-01-01']

In [84]:
df.sort_values('Date Manufactured')

,Name Â,Manufacturer,Date Manufactured,Players,Type,Theme
5375,Texan,Alben,1960-01-01,4.0,EM,American West
4520,Seven Seas,D. Gottlieb & Company,1960-01-01,2.0,EM,Deep Sea Fishing - Sailing - Relaxation
1032,Carnaval,Alben,1960-01-01,2.0,EM,Circus/Carnival
5373,Texan,Alben,1960-01-01,2.0,EM,American West
6103,World Series,Chicago Coin Machine Manufacturing Company,1960-01-01,1.0,EM,Sports - Baseball
2248,Golden Gloves,Williams Electronic Manufacturing Company,1960-01-05,1.0,EM,Sports - Boxing
3658,Official Baseball,Williams Electronic Manufacturing Company,1960-02-01,2.0,EM,Sports - Baseball
1497,Deluxe Official Baseball,Williams Electronic Manufacturing Company,1960-02-01,2.0,EM,Sports - Baseball
424,Bally Derby,Bally Manufacturing Corporation,1960-02-01,5.0,EM,Sports - Horse Racing
6091,World Beauties,D. Gottlieb & Company,1960-02-01,1.0,EM,Beauty Pageant
2752,Joker's Wild,Midway Manufacturing Company,1960-02-12,1.0,EM,Playing Cards
38,21,Williams Electronic Manufacturing Company,1960-02-24,1.0,EM,Cards/Gambling
1753,Eleven Belles,J. H. Keeney and Company Incorporated,1960-03-01,1.0,EM,Dancing - Pageantry
3534,Nags,Williams Electronic Manufacturing Company,1960-03-01,1.0,EM,Sports - Horse Racing
1491,Deluxe Baseball,United Manufacturing Company,1960-03-01,2.0,EM,Sports - Baseball
3063,Lite-A-Card,D. Gottlieb & Company,1960-03-01,2.0,EM,Playing Cards
5946,Wagon Train,D. Gottlieb & Company,1960-04-01,1.0,EM,American West
5374,Texan,D. Gottlieb & Company,1960-05-01,4.0,EM,American West
122,Acey Ducy,Auto Bell Novelty Company,1960-05-01,2.0,ME,Playing Cards
4514,Serenade,Williams Electronic Manufacturing Company,1960-05-23,2.0,EM,Music - Pirates - Singing - Women
3657,Official Baseball,Williams Electronic Manufacturing Company,1960-06-01,1.0,EM,Sports - Baseball
1443,Dancing Dolls,D. Gottlieb & Company,1960-06-01,1.0,EM,Music - Dancing
1454,Darts,Williams Electronic Manufacturing Company,1960-06-13,1.0,EM,Sports - Darts
5924,Viking,Williams Electronic Manufacturing Company,1960-06-28,2.0,EM,Norse History
1007,Captain Kidd,D. Gottlieb & Company,1960-07-01,2.0,EM,Historical - Pirates
2793,Jungle,Williams Electronic Manufacturing Company,1960-07-11,1.0,EM,Hunting - Safari
4977,Spot-A-Card,D. Gottlieb & Company,1960-08-01,1.0,EM,Cards - Gambling
3511,Music Man,Williams Electronic Manufacturing Company,1960-08-01,4.0,EM,Happiness - Marching Band - Music - Parades
474,Barrel Oâ Fun,Bally Manufacturing Corporation,1960-09-01,1.0,EM,Amusement Park - Carnival
3319,Melody Lane,D. Gottlieb & Company,1960-09-01,2.0,EM,Dancing - Girls - Pageantry - Singing - Women
...,...,...,...,...,...,...
4917,Spider-Man (Home Edition),"Stern Pinball, Incorporated",2016-11-01,4.0,SS,Licensed - Comics - Superheroes
517,Batman (66 Super Limited Edition),"Stern Pinball, Incorporated",2016-12-01,4.0,SS,Licensed - Comics - Superheroes - Television Show
516,Batman (66 Premium),"Stern Pinball, Incorporated",2016-12-01,4.0,SS,Licensed - Comics - Superheroes - Television Show
515,Batman (66 Limited Edition),"Stern Pinball, Incorporated",2016-12-01,4.0,SS,Licensed - Comics - Superheroes - Television Show
5632,Total Nuclear Annihilation,Spooky Pinball LLC,2017-01-01,4.0,SS,Warfare
143,Aerosmith (Pro),"Stern Pinball, Incorporated",2017-02-01,4.0,SS,Licensed Theme - Music â Singing
184,Alien (Standard Edition),"Heighway Pinball, Ltd.",2017-02-01,4.0,SS,Licensed Theme - Science Fiction
141,Aerosmith (Limited Edition),"Stern Pinball, Incorporated",2017-03-01,4.0,SS,Licensed Theme - Music â Singing
142,Aerosmith (Premium),"Stern Pinball, Incorporated",2017-04-01,4.0,SS,Licensed Theme - Music â Singing
105,AC/DC (Pro Vault Edition),"Stern Pinball, Incorporated",2017-05-01,4.0,SS,Licensed Theme - Music
5066,Star Wars (Pro),"Stern Pinball, Incorporated",2017-06-01,4.0,SS,Licensed Theme - Fantasy - Outer Space - Scien...
331,Attack From Mars (Remake Special Edition),Chicago Gaming Company,2017-06-01,4.0,SS,Aliens - Martians - Fantasy
1545,Dialed In! (Limited Edition),"Jersey Jack Pinball, Inc.",2017-07-01,4.0,SS,Disasters - Hero's Journey - Pop Culture
102,AC/DC (Premium Vault Edition),"Stern Pinball, Incorporated",2017-07-01,4.0,SS,Licensed Theme - Music
330,Attack From Mars (Remake Limited Edition),Chicago Gaming Company,2017-07-01,4.0,SS,Aliens - Martians - Fantasy
3025,Lexy Lightspeed Secret Agent Showdown,"Multimorphic, Inc.",2017-07-28,1.0,SS,Fantasy - Science Fiction
993,Cannon Lagoon,"Multimorphic, Inc.",2017-07-28,1.0,SS,Adventure - Pirates
471,Barnyard,"Multimorphic, Inc.",2017-07-28,1.0,SS,Farm Animals
3024,Lexy Lightspeed Escape From Earth,"Multimorphic, Inc.",2017-07-28,9.0,SS,Fantasy - Science Fiction
5068,Star Wars Limited Edition,"Stern Pinball, Incorporated",2017-08-01,4.0,SS,Licensed Theme - Fantasy - Outer Space - Scien...
1546,Dialed In! (Standard Edition),"Jersey Jack Pinball, Inc.",2017-08-01,4.0,SS,Disasters - Hero's Journey - Pop Culture
5065,Star Wars (Premium),"Stern Pinball, Incorporated",2017-08-01,4.0,SS,Licensed Theme - Fantasy - Outer Space - Scien...
1544,Dialed In! (Collectorâs Edition),"Jersey Jack Pinball, Inc.",2017-09-01,4.0,SS,Disasters - Hero's Journey - Pop Culture
2330,Guardians of the Galaxy (Pro),"Stern Pinball, Incorporated",2017-11-01,4.0,SS,Licensed Theme - Fictional Characters - Superh...
6173,Zombie League All Stars,Valley Dynamo,2017-12-01,2.0,SS,Sports - Baseball
2331,Guardians of the Galaxy Limited Edition,"Stern Pinball, Incorporated",2017-12-01,4.0,SS,Licensed Theme - Fictional Characters - Superh...
198,All Star Baseball,Valley Dynamo,2017-12-01,2.0,SS,Sports - Baseball
2329,Guardians of the Galaxy (Premium),"Stern Pinball, Incorporated",2017-12-01,4.0,SS,Licensed Theme - Fictional Characters - Superh...
2611,Houdini Master of Mystery,American Pinball Inc.,2017-12-30,4.0,SS,Historical Characters - Magic
101,AC/DC (LUCI Vault Edition),"Stern Pinball, Incorporated",2018-02-01,4.0,SS,Licensed Theme - Music

In [90]:
df = df.groupby('Theme').filter(lambda x: len(x) < 10 and len(x) > 2)

In [91]:
df.Theme.value_counts()

Space Exploration                                                 9
Sports - Snow Skiing                                              9
Fantasy - Outer Space                                             8
Sports - Golf                                                     8
World Places                                                      8
Music - Dancing                                                   8
Playing Cards - Poker                                             8
Sports - Pinball                                                  8
Fantasy - Licensed Theme - Wizard/Magic                           7
Music - Singing - Dancing                                         7
Celebrities - Licensed                                            7
Happiness - Music                                                 7
Outer Space - Science Fiction - Space Fantasy                     7
Happiness - Dancing                                               7
Cops and Robbers                                                  7
Fantasy - Licensed Theme                                          6
Adventure - Foreign Peoples                                       6
Sports - Motorcycles/Motocross                                    6
Carnival - Shooting Gallery                                       6
Travel                                                            6
Outer Space - Licensed Theme                                      6
Parachuting - Sports - Skydiving                                  6
World Cultures                                                    5
Myth and Legend                                                   5
Warfare                                                           5
American Places                                                   5
Adventure                                                         5
Historical Characters                                             5
Outer Space - Space Fantasy                                       5
Mythology                                                         5
                                                                 ..
Amusement Park                                                    3
Licensed Theme - Music â Singing                                3
Amusement Park - Roller Coasters                                  3
Sports - Football - Futbol - Soccer                               3
Aviation                                                          3
Horror - Supernatural                                             3
Fictional Characters                                              3
Pageantry                                                         3
Psychedelic                                                       3
Canadian West                                                     3
Celebrities â Licensed - Music                                  3
Celebrities - Music                                               3
Licensed Theme - Fantasy - Outer Space - Science Fiction          3
Automobiles - Cars - Travel - Licensed Theme                      3
Girls - Women                                                     3
Car Culture                                                       3
Happiness - Games                                                 3
Cards - Gambling                                                  3
Chess                                                             3
Hunting - Safari                                                  3
Sports - Bicycling                                                3
Sports - Fishing                                                  3
Music â Singing - Dancing                                       3
Adventure - Supernatural                                          3
Adventure - Fictional Characters                                  3
Martial Arts                                                      3
American West - Western                                           3
Gambling - Slot Machines                                          3
Recreation - Swimming - Singing - Dancing                         3
Licensed Theme - Outer Space - Science Fiction - Space Fantasy    3
Name: Theme, Length: 108, dtype: int64

In [96]:
df[df['Theme'] == 'Fantasy - Outer Space']

,Name Â,Manufacturer,Date Manufactured,Players,Type,Theme
908,Buck Rogers,"D. Gottlieb & Company, a Columbia Pictures Ind...",1980-01-01,4.0,SS,Fantasy - Outer Space
2117,Galaxy Ranger,Bally Manufacturing Corporation,1978-01-01,4.0,SS,Fantasy - Outer Space
3917,PINÂ·BOT,"Williams Electronics Games, Incorporated, a su...",1986-10-01,4.0,SS,Fantasy - Outer Space
3918,PINÂ·BOT,"Universal de Desarrollos Electronicos, S.A.",1987-01-01,4.0,SS,Fantasy - Outer Space
4857,Space Rider,Geiger-Automatenbau GmbH,1980-03-11,4.0,SS,Fantasy - Outer Space
5095,Stellar Airship,Geiger-Automatenbau GmbH,1979-01-01,4.0,SS,Fantasy - Outer Space
5453,The Machine: Bride of PinÂ·bot,"Williams Electronics Games, Incorporated, a su...",1991-02-01,4.0,SS,Fantasy - Outer Space
5454,The Machine: Bride of PinÂ·bot 2.0,Dutch Pinball,2014-11-01,4.0,SS,Fantasy - Outer Space

In [88]:
df.Manufacturer.value_counts()

D. Gottlieb & Company                                                               75
Bally Manufacturing Corporation                                                     57
Williams Electronics, Incorporated                                                  46
Stern Pinball, Incorporated                                                         43
Williams Electronic Manufacturing Company                                           32
Chicago Coin Machine Manufacturing Company                                          30
Recel S. A.                                                                         20
Playmatic                                                                           18
Williams Electronics Games, Incorporated, a subsidiary of WMS Ind., Incorporated    17
D. Gottlieb & Company, a Columbia Pictures Industries Company                       16
Zaccaria                                                                            14
Bally Midway Manufacturing Company                                                  13
Premier Technology                                                                  12
Midway Manufacturing Company, a subsidiary of WMS Industries, Incorporated          11
Stern Electronics, Incorporated                                                     11
Jersey Jack Pinball, Inc.                                                           10
Allied Leisure Industries, Incorporated                                              8
Industria (ElectromecÃ¡nica) de Recreativos S.A                                      8
Sega Enterprises, Ltd.                                                               8
Segasa d.b.a. Sonic                                                                  7
Data East Pinball, Incorporated                                                      7
Rally a.k.a. Rally Play Company                                                      7
Bally Wulff                                                                          6
Leisure & Allied Industries                                                          5
Sega Pinball, Incorporated                                                           5
Procedimientos ElectromagnÃ©ticos de Tanteo y Color                                  5
Dama S.R.L.                                                                          5
Midway Manufacturing Company                                                         5
Geiger-Automatenbau GmbH                                                             4
Chicago Gaming Company                                                               4
                                                                                    ..
Mirco Games, Incorporated                                                            1
Whizbang Pinball                                                                     1
Ripepi                                                                               1
Coffee-Mat Amusement Division                                                        1
Alben                                                                                1
Illinois Pin Ball Incorporated                                                       1
Interflip S. A.                                                                      1
Riot Pinball, LLC                                                                    1
Bill Port                                                                            1
Bromley, Inc.                                                                        1
Fascination Int., Incorporated                                                       1
Pinball Shop                                                                         1
Giorgio Massiero                                                                     1
Spinball S.A.L.                                                                      1
Grand Products Incorporated                                                          1
Christian Automatic                                                                  1
European Automaten Service                                                           1
Sentinel Inc.                                                                        1
Rowamet IndÃºstria EletrometalÃºrgica LTDA                                           1
Century Consolidated Industries Company                                              1
Elettrocoin                                                                          1
Coleco Industries, Inc.                                                              1
Dutch Pinball                                                                        1
Videodens                                                                            1
Creaciones e Investigaciones ElectrÃ³nicas, Sociedad Limitada                        1
Innovative Concepts in Entertainment, Inc.                                           1
Mayoni Enterprises                                                                   1
Ideas y DiseÃ±os, Sociedad AnÃ³nima                                                  1
Bensa                                                                                1
Manufacturas Automaticas Americanas                                                  1
Name: Manufacturer, Length: 101, dtype: int64