# Monterey Flipper Pinball Standings Projections

## Purpose
This notebook is used to project the final standings of the Monterey Flipper Pinball league.
The highest 5 weekly scores for each player are summed at the end of the season to produce a winner.
There are 10 weeks total, so you can drop up to 5 scores if you attend every week.


## TODO/Issues
- Possibly redo converting the json to a dataframe, there has to be a better way
- Projections fail if the average is taken over a player's best games
- API fails to pull all players in Winter 17 MFP league, (series_id = 475)
    - works now?
    - fails completely in MFP Fall 16, possibly because of the empty week
- required average doesn't work as expected before week 5

In [1]:
import pandas as pd
import numpy as np
import requests
import json
from collections import defaultdict

In [2]:
# Parameterized series_id for papermill
series_id = '2161' # Id number from the matchplay series

In [3]:
# Parameters
series_id = "2456"

In [4]:
matchplay_api = 'https://matchplay.events/data/'

In [5]:
series_url = str(matchplay_api)+'series/'+str(series_id)+'/standings'

In [6]:
#papermill_description=pull_from_matchplay

# Call the API
data = requests.get(series_url).json()['tournament_points']

In [7]:
#papermill_description=shaping_matchplay_data
data = [{**x, **x.pop('points')} for x in data]
df = pd.DataFrame(data).transpose().reset_index()
df.columns = df.loc[0]
df.rename(columns={'tournament_id': 'player_id'}, inplace=True)
df = df.iloc[2:]
points_df = df.set_index('player_id')

In [8]:
def pull_player_names(matchplay_df):
    tournament_ids = matchplay_df.columns
    tournament_url_a = 'https://matchplay.events/data/tournaments/'
    tournament_url_b = '/standings'

    player_names = {}
    for tournament_id in tournament_ids:
        tournament_url = tournament_url_a + str(tournament_id) + tournament_url_b
        r = requests.get(tournament_url)
        data = r.json()
        for player in data:
            if player['player_id'] not in player_names:
                player_names[str(player['player_id'])] = player['name']
    matchplay_df.index = matchplay_df.index.map(player_names)
    return matchplay_df

In [9]:
#papermill_description=pulling_player_names
points_df = pull_player_names(points_df)

In [10]:
num_weeks = points_df.shape[1]
weeks_left = 10 - num_weeks

if (int(series_id) < 1875):
    games_counted = 5
else:
    games_counted = 6

In [11]:


# Apply function that takes the row and does necessary computations for extra columns
def compute_projections(row):
    weeks_left = 10-num_weeks
    
    # Compute average score of all weeks
    row['avg_score'] = row[:num_weeks].mean()
    
    # Number of weeks played
    row['weeks_played'] = row[:num_weeks].count()
    
    # Find best five games for a player
    # Updated for Winter22, best six games now
    best_games = [points for points in row[:num_weeks] if points > 0]
    best_games.sort(reverse=True)
    best_games = best_games[:games_counted]
    
    # Exclude a players
    best_games_aa = [points for points in best_games if points >= row['avg_score']]
    best_games_aa.sort(reverse=True)    
    
    # Attendance totals
    row['avg_att'] = row['weeks_played']/num_weeks
    row['proj_att'] = round(row['avg_att']*10)
    row['weeks_left_att'] = row['proj_att'] - row['weeks_played']
    
    # Total number of points accumulated
    row['cur_total'] = sum([points for points in row[:num_weeks] if points > 0])

    
    
    # Find a player's current score, the metric by which players are judged at the end of the season
    row['current_score'] = sum(best_games)
    
    # Find a player's current result, the metric used by matchplay to show rank during season (Winter 20, fixed for winter22 change)
    # best (6-weeks_left) scores
    if 6-weeks_left < 1:
        row['cur_result'] = 0
    else:
        row['cur_result'] = sum(best_games[:6-weeks_left])
    
    

    # mean_adj_score: the points added to a player's projection to supplant their below average games
    # initialize variable to 0 for players that have 5 games above their average
    
    
    # If a player has six games above their average, no games are replaced by that average
    if len(best_games_aa) >= 6:
        row['kept_score'] = sum(best_games_aa[:6])
        row['proj_score'] = row['kept_score']
        row['mean_adj_score'] = 0
        row['proj_type'] = 'A'
        
    # Replace weeks below average with the average score, depending on how many weeks are left
    if len(best_games_aa) < 6:
        row['kept_score'] = sum(best_games_aa)
        if (6-len(best_games_aa)) <= weeks_left:
            row['mean_adj_score'] = (6-len(best_games_aa))*row['avg_score']
            row['proj_type'] = 'B'
        else:
            row['kept_score'] = sum(best_games[:(6-weeks_left)])
            row['mean_adj_score'] = weeks_left*row['avg_score']
            row['proj_type'] = 'C'
        # Project final score
        row['proj_score'] = row['kept_score'] + row['mean_adj_score']
    
    # Project attendance and adjust projection
    if len(best_games_aa) < 6:
        row['kept_score_att'] = sum(best_games_aa)
        if (5-len(best_games_aa) <= row['weeks_left_att']):
            row['mean_adj_score_att'] = (6-len(best_games_aa))*row['avg_score']
        else:
            row['kept_score_att'] = sum(best_games[:(6-int(row['weeks_left_att']))])
            row['mean_adj_score_att'] = int(row['weeks_left_att'])*row['avg_score']
        row['proj_score_att'] = row['kept_score_att'] + row['mean_adj_score_att']
    else:
        row['kept_score_att'] = row['kept_score']
        row['mean_adj_score_att'] = row['mean_adj_score']
        row['proj_score_att'] = row['kept_score_att'] + row['mean_adj_score_att']
       
    # Find a player's maximum possible score assuming they score a perfect 35 every remaining week
    if weeks_left < 6:
        row['max_score_possible'] = sum(best_games[:6-weeks_left]) + weeks_left*35
    else:
        row['max_score_possible'] = 6*35
    
    # The number of weeks of average score added to a player's projection,
    #   so the number of weeks the player would need to do above average to reach their projection
    if row['avg_score'] != 0:
        row['remaining_weeks_above_avg'] = (row['mean_adj_score']/row['avg_score'])
    
    # The score a player needs to beat in a future week to improve their score
    #row['score_to_beat'] = best_games[4]
    row['score_to_beat'] = 0
    if len(best_games) == 6:
        row['score_to_beat'] = best_games[-1]
    
    
    return row

In [12]:
#papermill_description=computing_projections
# Apply the calculations
final_points_df = points_df.apply(compute_projections, axis=1)

In [13]:
final_points_df.sort_values('proj_score', ascending = False, inplace=True)

In [14]:
current_leader = final_points_df.current_score.max()

# calculate the average a player must get in the remaining games to beat the leader
def compute_required_avg_win(row):
    if row['max_score_possible'] <= current_leader:
        row['required_avg_win'] = 0
    elif row['current_score'] == current_leader:
        row['required_avg_win'] = 0
    else:
        # Find best five games for a player
        best_games = [points for points in row[:num_weeks] if points > 0]
        best_games.sort(reverse=True)
        best_games = best_games[:5]
        row['required_avg_win'] = ((current_leader+1) - sum(best_games[:games_counted-weeks_left]))/weeks_left
    
    return row

In [15]:
#papermill_description=computing_required_avg_to_win
final_points_df = final_points_df.apply(compute_required_avg_win, axis=1)

In [16]:
final_points_df['score_rank'] = final_points_df.current_score.rank(method='first', ascending=False)

In [17]:
final_points_df[final_points_df.score_rank == 3].current_score[0]

80.0

In [18]:
current_third = final_points_df[final_points_df.score_rank == 3].current_score[0]

# calculate the average a player must get in the remaining games to beat third place, getting a trophy
def compute_required_avg_trophy(row):
    if row['current_score'] >= current_third:
        row['required_avg_trophy'] = 0
    elif row['max_score_possible'] < current_third:
        row['required_avg_trophy'] = 0
    elif row['current_score'] == current_third:
        row['required_avg_trophy'] = 0
    else:
        # Find best games_counted games for a player
        best_games = [points for points in row[:num_weeks] if points > 0]
        best_games.sort(reverse=True)
        best_games = best_games[:games_counted]
        row['required_avg_trophy'] = ((current_third) - sum(best_games[:games_counted-weeks_left]))/weeks_left
    
    return row

In [19]:
#papermill_description=computing_required_avg_to_trophy
final_points_df = final_points_df.apply(compute_required_avg_trophy, axis=1)

In [20]:
#scores = final_points_df.iloc[:,:final_points_df.columns.get_loc('avg_score')]

In [21]:
final_points_df.columns.get_loc('avg_score')

3

In [22]:
final_points_df

,91361,91363,91364,avg_score,weeks_played,avg_att,proj_att,weeks_left_att,cur_total,current_score,...,proj_score,kept_score_att,mean_adj_score_att,proj_score_att,max_score_possible,remaining_weeks_above_avg,score_to_beat,required_avg_win,score_rank,required_avg_trophy
player_id,,,,,,,,,,,,,,,,,,,,,
Xavier Marin,NaN,23.0,35.0,29.000000,2,0.666667,7,5,58.0,58.0,...,180.000000,35.0,145.000000,180.000000,175,5.0,0,6.714286,16.0,6.428571
Will Chernetsky,31.0,23.0,27.0,27.000000,3,1.000000,10,7,81.0,81.0,...,166.000000,58.0,108.000000,166.000000,175,4.0,0,0.000000,1.0,0.000000
Cary Carmichael,29.0,27.0,25.0,27.000000,3,1.000000,10,7,81.0,81.0,...,164.000000,56.0,108.000000,164.000000,175,4.0,0,0.000000,2.0,0.000000
Michael Mattsson,24.0,27.0,29.0,26.666667,3,1.000000,10,7,80.0,80.0,...,162.666667,56.0,106.666667,162.666667,175,4.0,0,3.714286,3.0,0.000000
John Tracey,25.0,27.0,27.0,26.333333,3,1.000000,10,7,79.0,79.0,...,159.333333,54.0,105.333333,159.333333,175,4.0,0,4.000000,4.0,3.714286
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Dexter Farm,NaN,19.0,7.0,13.000000,2,0.666667,7,5,26.0,26.0,...,84.000000,19.0,65.000000,84.000000,175,5.0,0,9.000000,40.0,8.714286
“Iris”,11.0,15.0,NaN,13.000000,2,0.666667,7,5,26.0,26.0,...,80.000000,15.0,65.000000,80.000000,175,5.0,0,9.571429,41.0,9.285714
Greg Bodnar,NaN,NaN,13.0,13.000000,1,0.333333,3,2,13.0,13.0,...,78.000000,13.0,26.000000,39.000000,175,5.0,0,11.714286,60.0,11.428571
Renata da Silva,NaN,11.0,NaN,11.000000,1,0.333333,3,2,11.0,11.0,...,66.000000,11.0,22.000000,33.000000,175,5.0,0,11.714286,61.0,11.428571
Whitney Clark,8.0,NaN,13.0,10.500000,2,0.666667,7,5,21.0,21.0,...,65.500000,13.0,52.500000,65.500000,175,5.0,0,9.857143,47.0,9.571429

In [23]:
max_scores = final_points_df.iloc[:,:final_points_df.columns.get_loc('avg_score')].max(skipna=True)

def get_weekly_win_count(row):
    row['weeks_won'] = sum(row[:row.index.get_loc('avg_score')] >= max_scores)
    return row

final_points_df = final_points_df.apply(get_weekly_win_count,axis=1)

In [24]:
max_scores

0
91361    31.0
91363    31.0
91364    35.0
dtype: float64

In [25]:
def top_n_score_columns(row,n=6):
    scores = row[:row.index.get_loc('avg_score')]
    scores = sorted(scores.fillna(0),reverse=True)
    if(len(scores) < n):
        n = len(scores)
    for i in range(1,n+1):
        row['top_score_'+str(i)] = scores[i-1]
    return row

final_points_df = final_points_df.apply(top_n_score_columns, axis=1)

In [26]:
final_points_df['league_rank'] = final_points_df.current_score.rank(method='min',ascending=False)

In [27]:
pd.set_option('display.max_columns',final_points_df.shape[1])
pd.set_option('display.max_rows',final_points_df.shape[0])

In [28]:
top_score = final_points_df.current_score.max()
final_points_df.current_score.max()

81.0

In [29]:
final_points_df.sort_values('current_score', ascending = False,inplace=True)
# final_points_df[final_points_df.max_score_possible >= top_score][['current_score','top_score_1','top_score_2','top_score_3','top_score_4','top_score_5','top_score_6',
#                        'avg_score','cur_total','proj_score','proj_score_att',                       
#                        'max_score_possible','required_avg_win','required_avg_trophy']]

In [30]:
#papermill_description=saving_csv
final_points_df.to_csv('mfp_league_'+str(series_id)+'_standings.csv', encoding='utf-8')

In [31]:
# final_points_df[['weeks_played','current_score','top_score_1','top_score_2','top_score_3','top_score_4','top_score_5','top_score_6',
#                        'avg_score','cur_total','proj_score','proj_score_att',                       
#                        'max_score_possible','required_avg_win','required_avg_trophy']]

In [32]:
final_points_df

,91361,91363,91364,avg_score,weeks_played,avg_att,proj_att,weeks_left_att,cur_total,current_score,cur_result,kept_score,mean_adj_score,proj_type,proj_score,kept_score_att,mean_adj_score_att,proj_score_att,max_score_possible,remaining_weeks_above_avg,score_to_beat,required_avg_win,score_rank,required_avg_trophy,weeks_won,top_score_1,top_score_2,top_score_3,league_rank
player_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Will Chernetsky,31.0,23.0,27.0,27.000000,3,1.000000,10,7,81.0,81.0,0,58.0,108.000000,B,166.000000,58.0,108.000000,166.000000,175,4.0,0,0.000000,1.0,0.000000,1,31.0,27.0,23.0,1.0
Cary Carmichael,29.0,27.0,25.0,27.000000,3,1.000000,10,7,81.0,81.0,0,56.0,108.000000,B,164.000000,56.0,108.000000,164.000000,175,4.0,0,0.000000,2.0,0.000000,0,29.0,27.0,25.0,1.0
Michael Mattsson,24.0,27.0,29.0,26.666667,3,1.000000,10,7,80.0,80.0,0,56.0,106.666667,B,162.666667,56.0,106.666667,162.666667,175,4.0,0,3.714286,3.0,0.000000,0,29.0,27.0,24.0,3.0
John Tracey,25.0,27.0,27.0,26.333333,3,1.000000,10,7,79.0,79.0,0,54.0,105.333333,B,159.333333,54.0,105.333333,159.333333,175,4.0,0,4.000000,4.0,3.714286,0,27.0,27.0,25.0,4.0
Matthew Talley,23.0,29.0,25.0,25.666667,3,1.000000,10,7,77.0,77.0,0,29.0,128.333333,B,157.333333,29.0,128.333333,157.333333,175,5.0,0,4.000000,5.0,3.714286,0,29.0,25.0,23.0,5.0
Nate King,21.0,31.0,23.0,25.000000,3,1.000000,10,7,75.0,75.0,0,31.0,125.000000,B,156.000000,31.0,125.000000,156.000000,175,5.0,0,4.000000,6.0,3.714286,1,31.0,23.0,21.0,6.0
Barry White CA,25.0,19.0,27.0,23.666667,3,1.000000,10,7,71.0,71.0,0,52.0,94.666667,B,146.666667,52.0,94.666667,146.666667,175,4.0,0,4.285714,7.0,4.000000,0,27.0,25.0,19.0,7.0
Nikki Carmichael,23.0,27.0,21.0,23.666667,3,1.000000,10,7,71.0,71.0,0,27.0,118.333333,B,145.333333,27.0,118.333333,145.333333,175,5.0,0,4.571429,8.0,4.285714,0,27.0,23.0,21.0,7.0
Harry Franklin,21.0,23.0,23.0,22.333333,3,1.000000,10,7,67.0,67.0,0,46.0,89.333333,B,135.333333,46.0,89.333333,135.333333,175,4.0,0,5.142857,9.0,4.857143,0,23.0,23.0,21.0,9.0
Philip Priddy,23.0,21.0,21.0,21.666667,3,1.000000,10,7,65.0,65.0,0,23.0,108.333333,B,131.333333,23.0,108.333333,131.333333,175,5.0,0,5.428571,10.0,5.142857,0,23.0,21.0,21.0,10.0
BeeOtch Westrum,20.0,21.0,23.0,21.333333,3,1.000000,10,7,64.0,64.0,0,23.0,106.666667,B,129.666667,23.0,106.666667,129.666667,175,5.0,0,5.428571,11.0,5.142857,0,23.0,21.0,20.0,11.0
Ikela Lagapa,29.0,15.0,19.0,21.000000,3,1.000000,10,7,63.0,63.0,0,29.0,105.000000,B,134.000000,29.0,105.000000,134.000000,175,5.0,0,4.857143,12.0,4.571429,0,29.0,19.0,15.0,12.0
Tyler Heath,21.0,17.0,23.0,20.333333,3,1.000000,10,7,61.0,61.0,0,44.0,81.333333,B,125.333333,44.0,81.333333,125.333333,175,4.0,0,5.428571,14.0,5.142857,0,23.0,21.0,17.0,13.0
Vincent Dane,23.0,15.0,23.0,20.333333,3,1.000000,10,7,61.0,61.0,0,46.0,81.333333,B,127.333333,46.0,81.333333,127.333333,175,4.0,0,5.142857,13.0,4.857143,0,23.0,23.0,15.0,13.0
Lucy Cachux,19.0,23.0,17.0,19.666667,3,1.000000,10,7,59.0,59.0,0,23.0,98.333333,B,121.333333,23.0,98.333333,121.333333,175,5.0,0,5.714286,15.0,5.428571,0,23.0,19.0,17.0,15.0
Xavier Marin,NaN,23.0,35.0,29.000000,2,0.666667,7,5,58.0,58.0,0,35.0,145.000000,B,180.000000,35.0,145.000000,180.000000,175,5.0,0,6.714286,16.0,6.428571,1,35.0,23.0,0.0,16.0
“RC”,19.0,17.0,20.0,18.666667,3,1.000000,10,7,56.0,56.0,0,39.0,74.666667,B,113.666667,39.0,74.666667,113.666667,175,4.0,0,6.142857,17.0,5.857143,0,20.0,19.0,17.0,17.0
Paige Peck,12.0,23.0,19.0,18.000000,3,1.000000,10,7,54.0,54.0,0,42.0,72.000000,B,114.000000,42.0,72.000000,114.000000,175,4.0,0,5.714286,18.0,5.428571,0,23.0,19.0,12.0,18.0
Tyler Powles,17.0,19.0,17.0,17.666667,3,1.000000,10,7,53.0,53.0,0,19.0,88.333333,B,107.333333,19.0,88.333333,107.333333,175,5.0,0,6.571429,19.0,6.285714,0,19.0,17.0,17.0,19.0
Greg Gorelick,27.0,25.0,NaN,26.000000,2,0.666667,7,5,52.0,52.0,0,27.0,130.000000,B,157.000000,27.0,130.000000,157.000000,175,5.0,0,7.857143,20.0,7.571429,0,27.0,25.0,0.0,20.0
Laura Masana,19.0,19.0,11.0,16.333333,3,1.000000,10,7,49.0,49.0,0,38.0,65.333333,B,103.333333,38.0,65.333333,103.333333,175,4.0,0,6.285714,21.0,6.000000,0,19.0,19.0,11.0,21.0
“Andreina”,14.0,21.0,14.0,16.333333,3,1.000000,10,7,49.0,49.0,0,21.0,81.666667,B,102.666667,21.0,81.666667,102.666667,175,5.0,0,6.714286,22.0,6.428571,0,21.0,14.0,14.0,21.0
Dan Irv,23.0,21.0,NaN,22.000000,2,0.666667,7,5,44.0,44.0,0,23.0,110.000000,B,133.000000,23.0,110.000000,133.000000,175,5.0,0,8.428571,23.0,8.142857,0,23.0,21.0,0.0,23.0
Matt Nielsen,20.0,NaN,23.0,21.500000,2,0.666667,7,5,43.0,43.0,0,23.0,107.500000,B,130.500000,23.0,107.500000,130.500000,175,5.0,0,8.428571,24.0,8.142857,0,23.0,20.0,0.0,24.0
Stone Simpson,27.0,NaN,14.0,20.500000,2,0.666667,7,5,41.0,41.0,0,27.0,102.500000,B,129.500000,27.0,102.500000,129.500000,175,5.0,0,7.857143,25.0,7.571429,0,27.0,14.0,0.0,25.0
Tim Priddy,17.0,7.0,16.0,13.333333,3,1.000000,10,7,40.0,40.0,0,33.0,53.333333,B,86.333333,33.0,53.333333,86.333333,175,4.0,0,7.000000,27.0,6.714286,0,17.0,16.0,7.0,26.0
Darren Roberts,NaN,19.0,21.0,20.000000,2,0.666667,7,5,40.0,40.0,0,21.0,100.000000,B,121.000000,21.0,100.000000,121.000000,175,5.0,0,8.714286,26.0,8.428571,0,21.0,19.0,0.0,26.0
Caitlin Campbell,23.0,NaN,15.0,19.000000,2,0.666667,7,5,38.0,38.0,0,23.0,95.000000,B,118.000000,23.0,95.000000,118.000000,175,5.0,0,8.428571,28.0,8.142857,0,23.0,15.0,0.0,28.0
Anthony Garcia CA,15.0,NaN,23.0,19.000000,2,0.666667,7,5,38.0,38.0,0,23.0,95.000000,B,118.000000,23.0,95.000000,118.000000,175,5.0,0,8.428571,29.0,8.142857,0,23.0,15.0,0.0,28.0
Brian Simpson,17.0,NaN,21.0,19.000000,2,0.666667,7,5,38.0,38.0,0,21.0,95.000000,B,116.000000,21.0,95.000000,116.000000,175,5.0,0,8.714286,30.0,8.428571,0,21.0,17.0,0.0,28.0
Ivy Simpson,18.0,NaN,19.0,18.500000,2,0.666667,7,5,37.0,37.0,0,19.0,92.500000,B,111.500000,19.0,92.500000,111.500000,175,5.0,0,9.000000,31.0,8.714286,0,19.0,18.0,0.0,31.0
Erika Svensson,NaN,15.0,19.0,17.000000,2,0.666667,7,5,34.0,34.0,0,19.0,85.000000,B,104.000000,19.0,85.000000,104.000000,175,5.0,0,9.000000,32.0,8.714286,0,19.0,15.0,0.0,32.0
Eric Garcia,21.0,12.0,NaN,16.500000,2,0.666667,7,5,33.0,33.0,0,21.0,82.500000,B,103.500000,21.0,82.500000,103.500000,175,5.0,0,8.714286,33.0,8.428571,0,21.0,12.0,0.0,33.0
Bobby Reagan,NaN,14.0,19.0,16.500000,2,0.666667,7,5,33.0,33.0,0,19.0,82.500000,B,101.500000,19.0,82.500000,101.500000,175,5.0,0,9.000000,34.0,8.714286,0,19.0,14.0,0.0,33.0
Lindsay McClure,NaN,21.0,11.0,16.000000,2,0.666667,7,5,32.0,32.0,0,21.0,80.000000,B,101.000000,21.0,80.000000,101.000000,175,5.0,0,8.714286,35.0,8.428571,0,21.0,11.0,0.0,35.0
Jasmine Phillips,11.0,NaN,19.0,15.000000,2,0.666667,7,5,30.0,30.0,0,19.0,75.000000,B,94.000000,19.0,75.000000,94.000000,175,5.0,0,9.000000,36.0,8.714286,0,19.0,11.0,0.0,36.0
Sneha Kolar,13.0,17.0,NaN,15.000000,2,0.666667,7,5,30.0,30.0,0,17.0,75.000000,B,92.000000,17.0,75.000000,92.000000,175,5.0,0,9.285714,37.0,9.000000,0,17.0,13.0,0.0,36.0
Glenn Howard-Erevia,17.0,NaN,12.0,14.500000,2,0.666667,7,5,29.0,29.0,0,17.0,72.500000,B,89.500000,17.0,72.500000,89.500000,175,5.0,0,9.285714,38.0,9.000000,0,17.0,12.0,0.0,38.0
Philip Ryder,21.0,6.0,NaN,13.500000,2,0.666667,7,5,27.0,27.0,0,21.0,67.500000,B,88.500000,21.0,67.500000,88.500000,175,5.0,0,8.714286,39.0,8.428571,0,21.0,6.0,0.0,39.0
Dexter Farm,NaN,19.0,7.0,13.000000,2,0.666667,7,5,26.0,26.0,0,19.0,65.000000,B,84.000000,19.0,65.000000,84.000000,175,5.0,0,9.000000,40.0,8.714286,0,19.0,7.0,0.0,40.0
“Iris”,11.0,15.0,NaN,13.000000,2,0.666667,7,5,26.0,26.0,0,15.0,65.000000,B,80.000000,15.0,65.000000,80.000000,175,5.0,0,9.571429,41.0,9.285714,0,15.0,11.0,0.0,40.0
Tasha Lindstrom,NaN,25.0,NaN,25.000000,1,0.333333,3,2,25.0,25.0,0,25.0,125.000000,B,150.000000,25.0,50.000000,75.000000,175,5.0,0,11.714286,43.0,11.428571,0,25.0,0.0,0.0,42.0
Tiffani Cabutage,NaN,NaN,25.0,25.000000,1,0.333333,3,2,25.0,25.0,0,25.0,125.000000,B,150.000000,25.0,50.000000,75.000000,175,5.0,0,11.714286,42.0,11.428571,0,25.0,0.0,0.0,42.0
Vincent Ruggiero,23.0,NaN,NaN,23.000000,1,0.333333,3,2,23.0,23.0,0,23.0,115.000000,B,138.000000,23.0,46.000000,69.000000,175,5.0,0,11.714286,44.0,11.428571,0,23.0,0.0,0.0,44.0
Whitney Clark,8.0,NaN,13.0,10.500000,2,0.666667,7,5,21.0,21.0,0,13.0,52.500000,B,65.500000,13.0,52.500000,65.500000,175,5.0,0,9.857143,47.0,9.571429,0,13.0,8.0,0.0,45.0
Barrett Lindstrom,NaN,21.0,NaN,21.000000,1,0.333333,3,2,21.0,21.0,0,21.0,105.000000,B,126.000000,21.0,42.000000,63.000000,175,5.0,0,11.714286,45.0,11.428571,0,21.0,0.0,0.0,45.0
Greg Dunlap,NaN,21.0,NaN,21.000000,1,0.333333,3,2,21.0,21.0,0,21.0,105.000000,B,126.000000,21.0,42.000000,63.000000,175,5.0,0,11.714286,46.0,11.428571,0,21.0,0.0,0.0,45.0
Mike Hubbard,19.0,NaN,NaN,19.000000,1,0.333333,3,2,19.0,19.0,0,19.0,95.000000,B,114.000000,19.0,38.000000,57.000000,175,5.0,0,11.714286,51.0,11.428571,0,19.0,0.0,0.0,48.0
Jonathan Linares,NaN,19.0,NaN,19.000000,1,0.333333,3,2,19.0,19.0,0,19.0,95.000000,B,114.000000,19.0,38.000000,57.000000,175,5.0,0,11.714286,50.0,11.428571,0,19.0,0.0,0.0,48.0
Tee Anderson,NaN,NaN,19.0,19.000000,1,0.333333,3,2,19.0,19.0,0,19.0,95.000000,B,114.000000,19.0,38.000000,57.000000,175,5.0,0,11.714286,49.0,11.428571,0,19.0,0.0,0.0,48.0
Todd Brammer,NaN,NaN,19.0,19.000000,1,0.333333,3,2,19.0,19.0,0,19.0,95.000000,B,114.000000,19.0,38.000000,57.000000,175,5.0,0,11.714286,48.0,11.428571,0,19.0,0.0,0.0,48.0
Jose Eschevarria,NaN,17.0,NaN,17.000000,1,0.333333,3,2,17.0,17.0,0,17.0,85.000000,B,102.000000,17.0,34.000000,51.000000,175,5.0,0,11.714286,52.0,11.428571,0,17.0,0.0,0.0,52.0
Jim Dismukes,17.0,NaN,NaN,17.000000,1,0.333333,3,2,17.0,17.0,0,17.0,85.000000,B,102.000000,17.0,34.000000,51.000000,175,5.0,0,11.714286,53.0,11.428571,0,17.0,0.0,0.0,52.0
Sam Stanko,NaN,NaN,16.0,16.000000,1,0.333333,3,2,16.0,16.0,0,16.0,80.000000,B,96.000000,16.0,32.000000,48.000000,175,5.0,0,11.714286,54.0,11.428571,0,16.0,0.0,0.0,54.0
Amy Wolfrum,16.0,NaN,NaN,16.000000,1,0.333333,3,2,16.0,16.0,0,16.0,80.000000,B,96.000000,16.0,32.000000,48.000000,175,5.0,0,11.714286,55.0,11.428571,0,16.0,0.0,0.0,54.0
Linda G,NaN,16.0,NaN,16.000000,1,0.333333,3,2,16.0,16.0,0,16.0,80.000000,B,96.000000,16.0,32.000000,48.000000,175,5.0,0,11.714286,56.0,11.428571,0,16.0,0.0,0.0,54.0
Tammy Ballinger,15.0,NaN,NaN,15.000000,1,0.333333,3,2,15.0,15.0,0,15.0,75.000000,B,90.000000,15.0,30.000000,45.000000,175,5.0,0,11.714286,57.0,11.428571,0,15.0,0.0,0.0,57.0
Rene Garcia,15.0,NaN,NaN,15.000000,1,0.333333,3,2,15.0,15.0,0,15.0,75.000000,B,90.000000,15.0,30.000000,45.000000,175,5.0,0,11.714286,58.0,11.428571,0,15.0,0.0,0.0,57.0
Caitlin Westmoreland,NaN,NaN,15.0,15.000000,1,0.333333,3,2,15.0,15.0,0,15.0,75.000000,B,90.000000,15.0,30.000000,45.000000,175,5.0,0,11.714286,59.0,11.428571,0,15.0,0.0,0.0,57.0
Greg Bodnar,NaN,NaN,13.0,13.000000,1,0.333333,3,2,13.0,13.0,0,13.0,65.000000,B,78.000000,13.0,26.000000,39.000000,175,5.0,0,11.714286,60.0,11.428571,0,13.0,0.0,0.0,60.0
Renata da Silva,NaN,11.0,NaN,11.000000,1,0.333333,3,2,11.0,11.0,0,11.0,55.000000,B,66.000000,11.0,22.000000,33.000000,175,5.0,0,11.714286,61.0,11.428571,0,11.0,0.0,0.0,61.0

In [33]:
final_points_df[final_points_df.weeks_played == 4]

Empty DataFrame
Columns: [91361, 91363, 91364, avg_score, weeks_played, avg_att, proj_att, weeks_left_att, cur_total, current_score, cur_result, kept_score, mean_adj_score, proj_type, proj_score, kept_score_att, mean_adj_score_att, proj_score_att, max_score_possible, remaining_weeks_above_avg, score_to_beat, required_avg_win, score_rank, required_avg_trophy, weeks_won, top_score_1, top_score_2, top_score_3, league_rank]
Index: []